/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /u/s/h/shrirams/bugsparser/Parser/BUGS.g
 *     -                            On : 2013-01-04 16:08:05
 *     -                 for the lexer : BUGSLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "BUGSLexer.h"
/* ----------------------------------------- */


/** String literals used by BUGSLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x61, 0x62, 0x73, 0x28,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x64, 0x62, 0x65, 0x72, 0x6E, 0x28,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x64, 0x62, 0x65, 0x74, 0x61, 0x28,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x43, 0x28,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x49, 0x28,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x63, 0x6C, 0x6F, 0x67, 0x6C, 0x6F, 0x67, 0x28,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x64, 0x64, 0x69, 0x72, 0x69, 0x63, 0x68, 0x28,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x66, 0x6F, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x69, 0x6E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x69, 0x6E, 0x76, 0x65, 0x72, 0x73, 0x65, 0x28,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x3C, 0x2D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x6C, 0x6F, 0x67, 0x69, 0x74, 0x28,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_13[]  = { 0x6C, 0x6F, 0x67, 0x28,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_14[]  = { 0x6D, 0x6F, 0x64, 0x65, 0x6C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_15[]  = { 0x64, 0x6D, 0x75, 0x6C, 0x74, 0x69, 0x28,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_16[]  = { 0x70, 0x72, 0x6F, 0x62, 0x69, 0x74, 0x28,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_17[]  = { 0x54, 0x28,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pBUGSLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pBUGSLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pBUGSLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pBUGSLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mABSOPENBRACKET    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mBERNOULLIOPENBRACKET    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mBETAOPENBRACKET    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mCENSORBEGINWITHC    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mCENSORBEGINWITHI    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mCLOGLOGOPENBRACKET    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mCLOSEBRACE    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mCLOSEBRACKET    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mCLOSESQUAREBRACKET    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mCOLON    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mCOMMA    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mDIRICHLETOPENBRACKET    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mDIV    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mFORSTART    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mIN    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mINVERSEOPENBRACKET    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mLEFTPOINTER    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mLOGITOPENBRACKET    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mLOGOPENBRACKET    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mMINUS    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mMODEL    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mMULT    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mMUTLTINOMIALOPENBRACKET    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mOPENBRACE    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mOPENBRACKET    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mOPENSQUAREBRACKET    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mPLUS    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mPROBITOPENBRACKET    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mTILDE    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mTRUNCATIONBEGIN    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mCONSTANTINT    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mNODENAME    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mCONSTANTVALUE    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mWHITESPACE    (pBUGSLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pBUGSLexer ctx);
static void	BUGSLexerFree(pBUGSLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
BUGSLexerFree  (pBUGSLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
BUGSLexerReset (pBUGSLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/u/s/h/shrirams/bugsparser/Parser/BUGS.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called BUGSLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pBUGSLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pBUGSLexer BUGSLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return BUGSLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called BUGSLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pBUGSLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pBUGSLexer BUGSLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pBUGSLexer ctx; // Context structure we will build and return

    ctx = (pBUGSLexer) ANTLR3_CALLOC(1, sizeof(BUGSLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in BUGSLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our BUGSLexer interface
     */
    ctx->mABSOPENBRACKET	= mABSOPENBRACKET;
    ctx->mBERNOULLIOPENBRACKET	= mBERNOULLIOPENBRACKET;
    ctx->mBETAOPENBRACKET	= mBETAOPENBRACKET;
    ctx->mCENSORBEGINWITHC	= mCENSORBEGINWITHC;
    ctx->mCENSORBEGINWITHI	= mCENSORBEGINWITHI;
    ctx->mCLOGLOGOPENBRACKET	= mCLOGLOGOPENBRACKET;
    ctx->mCLOSEBRACE	= mCLOSEBRACE;
    ctx->mCLOSEBRACKET	= mCLOSEBRACKET;
    ctx->mCLOSESQUAREBRACKET	= mCLOSESQUAREBRACKET;
    ctx->mCOLON	= mCOLON;
    ctx->mCOMMA	= mCOMMA;
    ctx->mDIRICHLETOPENBRACKET	= mDIRICHLETOPENBRACKET;
    ctx->mDIV	= mDIV;
    ctx->mFORSTART	= mFORSTART;
    ctx->mIN	= mIN;
    ctx->mINVERSEOPENBRACKET	= mINVERSEOPENBRACKET;
    ctx->mLEFTPOINTER	= mLEFTPOINTER;
    ctx->mLOGITOPENBRACKET	= mLOGITOPENBRACKET;
    ctx->mLOGOPENBRACKET	= mLOGOPENBRACKET;
    ctx->mMINUS	= mMINUS;
    ctx->mMODEL	= mMODEL;
    ctx->mMULT	= mMULT;
    ctx->mMUTLTINOMIALOPENBRACKET	= mMUTLTINOMIALOPENBRACKET;
    ctx->mOPENBRACE	= mOPENBRACE;
    ctx->mOPENBRACKET	= mOPENBRACKET;
    ctx->mOPENSQUAREBRACKET	= mOPENSQUAREBRACKET;
    ctx->mPLUS	= mPLUS;
    ctx->mPROBITOPENBRACKET	= mPROBITOPENBRACKET;
    ctx->mTILDE	= mTILDE;
    ctx->mTRUNCATIONBEGIN	= mTRUNCATIONBEGIN;
    ctx->mCONSTANTINT	= mCONSTANTINT;
    ctx->mNODENAME	= mNODENAME;
    ctx->mCONSTANTVALUE	= mCONSTANTVALUE;
    ctx->mWHITESPACE	= mWHITESPACE;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= BUGSLexerFree;
    ctx->reset          = BUGSLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( ABSOPENBRACKET | BERNOULLIOPENBRACKET | BETAOPENBRACKET | CENSORBEGINWITHC | CENSORBEGINWITHI | CLOGLOGOPENBRACKET | CLOSEBRACE | CLOSEBRACKET | CLOSESQUAREBRACKET | COLON | COMMA | DIRICHLETOPENBRACKET | DIV | FORSTART | IN | INVERSEOPENBRACKET | LEFTPOINTER | LOGITOPENBRACKET | LOGOPENBRACKET | MINUS | MODEL | MULT | MUTLTINOMIALOPENBRACKET | OPENBRACE | OPENBRACKET | OPENSQUAREBRACKET | PLUS | PROBITOPENBRACKET | TILDE | TRUNCATIONBEGIN | CONSTANTINT | NODENAME | CONSTANTVALUE | WHITESPACE );
 */
static const ANTLR3_INT32 dfa11_eot[95] =
    {
	-1, 27, 27, 27, 27, 27, -1, -1, -1, -1, -1, -1, 27, 27, -1, 27, 39, 27, 
	-1, -1, -1, -1, 42, 27, -1, 27, 45, -1, -1, 27, 27, 27, 27, -1, -1, 27, 
	27, 53, 27, -1, -1, 27, -1, 27, -1, -1, 27, 27, 27, 27, 27, 63, 27, -1, 
	27, 27, 27, -1, 27, 27, 27, 27, 27, -1, 27, 27, -1, 27, 27, 27, 27, 27, 
	27, 27, 27, 27, 85, 27, -1, -1, 27, 27, 27, 27, -1, -1, 27, 27, -1, 27, 
	27, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa11_eof[95] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa11_min[95] =
    {
	9, 98, 98, 40, 40, 108, -1, -1, -1, -1, -1, -1, 111, 110, -1, 111, 48, 
	111, -1, -1, -1, -1, 48, 114, -1, 40, 46, -1, -1, 115, 101, 105, 117, -1, 
	-1, 111, 114, 46, 103, -1, -1, 100, -1, 111, -1, -1, 40, 114, 114, 108, 
	103, 46, 101, -1, 40, 101, 98, -1, 110, 97, 105, 116, 108, -1, 114, 116, 
	-1, 108, 105, 40, 40, 99, 105, 111, 115, 40, 46, 116, -1, -1, 104, 40, 
	103, 101, -1, -1, 40, 40, -1, 40, 40, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa11_max[95] =
    {
	126, 98, 109, 40, 40, 108, -1, -1, -1, -1, -1, -1, 111, 110, -1, 111, 57, 
	111, -1, -1, -1, -1, 57, 114, -1, 40, 69, -1, -1, 115, 101, 105, 117, -1, 
	-1, 111, 114, 122, 103, -1, -1, 100, -1, 111, -1, -1, 40, 116, 114, 108, 
	103, 122, 101, -1, 105, 101, 98, -1, 110, 97, 105, 116, 108, -1, 114, 116, 
	-1, 108, 105, 40, 40, 99, 105, 111, 115, 40, 122, 116, -1, -1, 104, 40, 
	103, 101, -1, -1, 40, 40, -1, 40, 40, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa11_accept[95] =
    {
	-1, -1, -1, -1, -1, -1, 7, 8, 9, 10, 11, 13, -1, -1, 17, -1, -1, -1, 22, 
	24, 25, 26, -1, -1, 29, -1, -1, 32, 34, -1, -1, -1, -1, 4, 5, -1, -1, -1, 
	-1, 20, 33, -1, 27, -1, 30, 31, -1, -1, -1, -1, -1, -1, -1, 15, -1, -1, 
	-1, 1, -1, -1, -1, -1, -1, 14, -1, -1, 19, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, 2, 3, -1, -1, -1, -1, 18, 21, -1, -1, 23, -1, -1, 28, 12, 
	6, 16
    };
static const ANTLR3_INT32 dfa11_special[95] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa11_T_empty	    NULL

static const ANTLR3_INT32 dfa11_T0[] =
    {
	40, -1, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 40
    };

static const ANTLR3_INT32 dfa11_T1[] =
    {
	64
    };

static const ANTLR3_INT32 dfa11_T2[] =
    {
	74
    };

static const ANTLR3_INT32 dfa11_T3[] =
    {
	83
    };

static const ANTLR3_INT32 dfa11_T4[] =
    {
	90
    };

static const ANTLR3_INT32 dfa11_T5[] =
    {
	47
    };

static const ANTLR3_INT32 dfa11_T6[] =
    {
	94
    };

static const ANTLR3_INT32 dfa11_T7[] =
    {
	58, -1, 59
    };

static const ANTLR3_INT32 dfa11_T8[] =
    {
	27, -1, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, -1, -1, -1, -1, -1, -1, 
	-1, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 
	27, 27, 27, 27, 27, 27, 27, 27, 27, -1, -1, -1, -1, -1, -1, 27, 27, 27, 
	27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 
	27, 27, 27, 27, 27
    };

static const ANTLR3_INT32 dfa11_T9[] =
    {
	51
    };

static const ANTLR3_INT32 dfa11_T10[] =
    {
	57
    };

static const ANTLR3_INT32 dfa11_T11[] =
    {
	36
    };

static const ANTLR3_INT32 dfa11_T12[] =
    {
	46
    };

static const ANTLR3_INT32 dfa11_T13[] =
    {
	28, 28, -1, 28, 28, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 28, -1, -1, -1, -1, -1, -1, -1, 20, 7, 18, 22, 10, 
	16, -1, 11, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 9, 28, 14, -1, -1, 
	-1, -1, 27, 27, 3, 27, 27, 27, 27, 27, 4, 27, 27, 27, 27, 27, 27, 27, 27, 
	27, 27, 25, 27, 27, 27, 27, 27, 27, 21, -1, 8, -1, -1, -1, 1, 27, 5, 2, 
	27, 12, 27, 27, 13, 27, 27, 15, 17, 27, 27, 23, 27, 27, 27, 27, 27, 27, 
	27, 27, 27, 27, 19, -1, 6, 24
    };

static const ANTLR3_INT32 dfa11_T14[] =
    {
	76
    };

static const ANTLR3_INT32 dfa11_T15[] =
    {
	78
    };

static const ANTLR3_INT32 dfa11_T16[] =
    {
	69
    };

static const ANTLR3_INT32 dfa11_T17[] =
    {
	55
    };

static const ANTLR3_INT32 dfa11_T18[] =
    {
	67
    };

static const ANTLR3_INT32 dfa11_T19[] =
    {
	84
    };

static const ANTLR3_INT32 dfa11_T20[] =
    {
	75
    };

static const ANTLR3_INT32 dfa11_T21[] =
    {
	27, -1, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, -1, -1, -1, -1, -1, -1, 
	-1, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 
	27, 27, 27, 27, 27, 27, 27, 27, 27, -1, -1, -1, -1, -1, -1, 27, 27, 27, 
	27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 
	52, 27, 27, 27, 27
    };

static const ANTLR3_INT32 dfa11_T22[] =
    {
	77
    };

static const ANTLR3_INT32 dfa11_T23[] =
    {
	86
    };

static const ANTLR3_INT32 dfa11_T24[] =
    {
	91
    };

static const ANTLR3_INT32 dfa11_T25[] =
    {
	50
    };

static const ANTLR3_INT32 dfa11_T26[] =
    {
	44
    };

static const ANTLR3_INT32 dfa11_T27[] =
    {
	56
    };

static const ANTLR3_INT32 dfa11_T28[] =
    {
	68
    };

static const ANTLR3_INT32 dfa11_T29[] =
    {
	93
    };

static const ANTLR3_INT32 dfa11_T30[] =
    {
	43
    };

static const ANTLR3_INT32 dfa11_T31[] =
    {
	40, 40, 40, 40, 40, 40, 40, 40, 40, 40
    };

static const ANTLR3_INT32 dfa11_T32[] =
    {
	73
    };

static const ANTLR3_INT32 dfa11_T33[] =
    {
	62
    };

static const ANTLR3_INT32 dfa11_T34[] =
    {
	89
    };

static const ANTLR3_INT32 dfa11_T35[] =
    {
	82
    };

static const ANTLR3_INT32 dfa11_T36[] =
    {
	33
    };

static const ANTLR3_INT32 dfa11_T37[] =
    {
	70
    };

static const ANTLR3_INT32 dfa11_T38[] =
    {
	38
    };

static const ANTLR3_INT32 dfa11_T39[] =
    {
	79
    };

static const ANTLR3_INT32 dfa11_T40[] =
    {
	88
    };

static const ANTLR3_INT32 dfa11_T41[] =
    {
	54
    };

static const ANTLR3_INT32 dfa11_T42[] =
    {
	34
    };

static const ANTLR3_INT32 dfa11_T43[] =
    {
	61
    };

static const ANTLR3_INT32 dfa11_T44[] =
    {
	49
    };

static const ANTLR3_INT32 dfa11_T45[] =
    {
	81
    };

static const ANTLR3_INT32 dfa11_T46[] =
    {
	72
    };

static const ANTLR3_INT32 dfa11_T47[] =
    {
	30, -1, 31, -1, -1, -1, -1, -1, -1, -1, -1, 32
    };

static const ANTLR3_INT32 dfa11_T48[] =
    {
	35
    };

static const ANTLR3_INT32 dfa11_T49[] =
    {
	60
    };

static const ANTLR3_INT32 dfa11_T50[] =
    {
	48
    };

static const ANTLR3_INT32 dfa11_T51[] =
    {
	66, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 65
    };

static const ANTLR3_INT32 dfa11_T52[] =
    {
	37
    };

static const ANTLR3_INT32 dfa11_T53[] =
    {
	92
    };

static const ANTLR3_INT32 dfa11_T54[] =
    {
	87
    };

static const ANTLR3_INT32 dfa11_T55[] =
    {
	80
    };

static const ANTLR3_INT32 dfa11_T56[] =
    {
	71
    };

static const ANTLR3_INT32 dfa11_T57[] =
    {
	41
    };

static const ANTLR3_INT32 dfa11_T58[] =
    {
	29
    };


/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa11_transitions[] =
{
    dfa11_T13, dfa11_T58, dfa11_T47, dfa11_T36, dfa11_T42, dfa11_T48, NULL, 
    NULL, NULL, NULL, NULL, NULL, dfa11_T11, dfa11_T52, NULL, dfa11_T38, 
    dfa11_T31, dfa11_T57, NULL, NULL, NULL, NULL, dfa11_T31, dfa11_T30, 
    NULL, dfa11_T26, dfa11_T0, NULL, NULL, dfa11_T12, dfa11_T5, dfa11_T50, 
    dfa11_T44, NULL, NULL, dfa11_T25, dfa11_T9, dfa11_T21, dfa11_T41, NULL, 
    NULL, dfa11_T17, NULL, dfa11_T27, NULL, NULL, dfa11_T10, dfa11_T7, dfa11_T49, 
    dfa11_T43, dfa11_T33, dfa11_T8, dfa11_T1, NULL, dfa11_T51, dfa11_T18, 
    dfa11_T28, NULL, dfa11_T16, dfa11_T37, dfa11_T56, dfa11_T46, dfa11_T32, 
    NULL, dfa11_T2, dfa11_T20, NULL, dfa11_T14, dfa11_T22, dfa11_T15, dfa11_T39, 
    dfa11_T55, dfa11_T45, dfa11_T35, dfa11_T3, dfa11_T19, dfa11_T8, dfa11_T23, 
    NULL, NULL, dfa11_T54, dfa11_T40, dfa11_T34, dfa11_T4, NULL, NULL, dfa11_T24, 
    dfa11_T53, NULL, dfa11_T29, dfa11_T6, NULL, NULL, NULL, NULL
};


/* Declare tracking structure for Cyclic DFA 11
 */
static
ANTLR3_CYCLIC_DFA cdfa11
    =	{
	    11,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1:1: Tokens : ( ABSOPENBRACKET | BERNOULLIOPENBRACKET | BETAOPENBRACKET | CENSORBEGINWITHC | CENSORBEGINWITHI | CLOGLOGOPENBRACKET | CLOSEBRACE | CLOSEBRACKET | CLOSESQUAREBRACKET | COLON | COMMA | DIRICHLETOPENBRACKET | DIV | FORSTART | IN | INVERSEOPENBRACKET | LEFTPOINTER | LOGITOPENBRACKET | LOGOPENBRACKET | MINUS | MODEL | MULT | MUTLTINOMIALOPENBRACKET | OPENBRACE | OPENBRACKET | OPENSQUAREBRACKET | PLUS | PROBITOPENBRACKET | TILDE | TRUNCATIONBEGIN | CONSTANTINT | NODENAME | CONSTANTVALUE | WHITESPACE );",
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/

	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa11_eot,	    /* EOT table			    */
	    dfa11_eof,	    /* EOF table			    */
	    dfa11_min,	    /* Minimum tokens for each state    */
	    dfa11_max,	    /* Maximum tokens for each state    */
	    dfa11_accept,	/* Accept table			    */
	    dfa11_special,	/* Special transition states	    */
	    dfa11_transitions	/* Table of transition tables	    */

	};
/* End of Cyclic DFA 11
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:16: ( 'abs(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ABSOPENBRACKET
 *
 * Looks to match the characters the constitute the token ABSOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mABSOPENBRACKET(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ABSOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:7:16: ( 'abs(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:7:18: 'abs('
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleABSOPENBRACKETEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleABSOPENBRACKETEx; /* Prevent compiler warnings */
    ruleABSOPENBRACKETEx: ;

}
// $ANTLR end ABSOPENBRACKET

//   Comes from: 8:22: ( 'dbern(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BERNOULLIOPENBRACKET
 *
 * Looks to match the characters the constitute the token BERNOULLIOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBERNOULLIOPENBRACKET(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BERNOULLIOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:8:22: ( 'dbern(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:8:24: 'dbern('
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleBERNOULLIOPENBRACKETEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBERNOULLIOPENBRACKETEx; /* Prevent compiler warnings */
    ruleBERNOULLIOPENBRACKETEx: ;

}
// $ANTLR end BERNOULLIOPENBRACKET

//   Comes from: 9:17: ( 'dbeta(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BETAOPENBRACKET
 *
 * Looks to match the characters the constitute the token BETAOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mBETAOPENBRACKET(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = BETAOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:9:17: ( 'dbeta(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:9:19: 'dbeta('
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleBETAOPENBRACKETEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleBETAOPENBRACKETEx; /* Prevent compiler warnings */
    ruleBETAOPENBRACKETEx: ;

}
// $ANTLR end BETAOPENBRACKET

//   Comes from: 10:18: ( 'C(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CENSORBEGINWITHC
 *
 * Looks to match the characters the constitute the token CENSORBEGINWITHC
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCENSORBEGINWITHC(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CENSORBEGINWITHC;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:10:18: ( 'C(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:10:20: 'C('
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleCENSORBEGINWITHCEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCENSORBEGINWITHCEx; /* Prevent compiler warnings */
    ruleCENSORBEGINWITHCEx: ;

}
// $ANTLR end CENSORBEGINWITHC

//   Comes from: 11:18: ( 'I(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CENSORBEGINWITHI
 *
 * Looks to match the characters the constitute the token CENSORBEGINWITHI
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCENSORBEGINWITHI(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CENSORBEGINWITHI;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:11:18: ( 'I(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:11:20: 'I('
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleCENSORBEGINWITHIEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCENSORBEGINWITHIEx; /* Prevent compiler warnings */
    ruleCENSORBEGINWITHIEx: ;

}
// $ANTLR end CENSORBEGINWITHI

//   Comes from: 12:20: ( 'cloglog(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CLOGLOGOPENBRACKET
 *
 * Looks to match the characters the constitute the token CLOGLOGOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCLOGLOGOPENBRACKET(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CLOGLOGOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:12:20: ( 'cloglog(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:12:22: 'cloglog('
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleCLOGLOGOPENBRACKETEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCLOGLOGOPENBRACKETEx; /* Prevent compiler warnings */
    ruleCLOGLOGOPENBRACKETEx: ;

}
// $ANTLR end CLOGLOGOPENBRACKET

//   Comes from: 13:12: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CLOSEBRACE
 *
 * Looks to match the characters the constitute the token CLOSEBRACE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCLOSEBRACE(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CLOSEBRACE;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:13:12: ( '}' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:13:14: '}'
    {
        MATCHC('}');
        if  (HASEXCEPTION())
        {
            goto ruleCLOSEBRACEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCLOSEBRACEEx; /* Prevent compiler warnings */
    ruleCLOSEBRACEEx: ;

}
// $ANTLR end CLOSEBRACE

//   Comes from: 14:14: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CLOSEBRACKET
 *
 * Looks to match the characters the constitute the token CLOSEBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCLOSEBRACKET(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CLOSEBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:14:14: ( ')' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:14:16: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto ruleCLOSEBRACKETEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCLOSEBRACKETEx; /* Prevent compiler warnings */
    ruleCLOSEBRACKETEx: ;

}
// $ANTLR end CLOSEBRACKET

//   Comes from: 15:20: ( ']' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CLOSESQUAREBRACKET
 *
 * Looks to match the characters the constitute the token CLOSESQUAREBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCLOSESQUAREBRACKET(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CLOSESQUAREBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:15:20: ( ']' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:15:22: ']'
    {
        MATCHC(']');
        if  (HASEXCEPTION())
        {
            goto ruleCLOSESQUAREBRACKETEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCLOSESQUAREBRACKETEx; /* Prevent compiler warnings */
    ruleCLOSESQUAREBRACKETEx: ;

}
// $ANTLR end CLOSESQUAREBRACKET

//   Comes from: 16:7: ( ':' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COLON
 *
 * Looks to match the characters the constitute the token COLON
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOLON(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COLON;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:16:7: ( ':' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:16:9: ':'
    {
        MATCHC(':');
        if  (HASEXCEPTION())
        {
            goto ruleCOLONEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCOLONEx; /* Prevent compiler warnings */
    ruleCOLONEx: ;

}
// $ANTLR end COLON

//   Comes from: 17:7: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMA
 *
 * Looks to match the characters the constitute the token COMMA
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOMMA(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COMMA;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:17:7: ( ',' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:17:9: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleCOMMAEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCOMMAEx; /* Prevent compiler warnings */
    ruleCOMMAEx: ;

}
// $ANTLR end COMMA

//   Comes from: 18:22: ( 'ddirich(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DIRICHLETOPENBRACKET
 *
 * Looks to match the characters the constitute the token DIRICHLETOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDIRICHLETOPENBRACKET(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DIRICHLETOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:18:22: ( 'ddirich(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:18:24: 'ddirich('
    {
        MATCHS(lit_7);
        if  (HASEXCEPTION())
        {
            goto ruleDIRICHLETOPENBRACKETEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDIRICHLETOPENBRACKETEx; /* Prevent compiler warnings */
    ruleDIRICHLETOPENBRACKETEx: ;

}
// $ANTLR end DIRICHLETOPENBRACKET

//   Comes from: 19:5: ( '/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DIV
 *
 * Looks to match the characters the constitute the token DIV
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDIV(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DIV;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:19:5: ( '/' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:19:7: '/'
    {
        MATCHC('/');
        if  (HASEXCEPTION())
        {
            goto ruleDIVEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDIVEx; /* Prevent compiler warnings */
    ruleDIVEx: ;

}
// $ANTLR end DIV

//   Comes from: 20:10: ( 'for' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start FORSTART
 *
 * Looks to match the characters the constitute the token FORSTART
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mFORSTART(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = FORSTART;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:20:10: ( 'for' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:20:12: 'for'
    {
        MATCHS(lit_8);
        if  (HASEXCEPTION())
        {
            goto ruleFORSTARTEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleFORSTARTEx; /* Prevent compiler warnings */
    ruleFORSTARTEx: ;

}
// $ANTLR end FORSTART

//   Comes from: 21:4: ( 'in' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start IN
 *
 * Looks to match the characters the constitute the token IN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mIN(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = IN;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:21:4: ( 'in' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:21:6: 'in'
    {
        MATCHS(lit_9);
        if  (HASEXCEPTION())
        {
            goto ruleINEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleINEx; /* Prevent compiler warnings */
    ruleINEx: ;

}
// $ANTLR end IN

//   Comes from: 22:20: ( 'inverse(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INVERSEOPENBRACKET
 *
 * Looks to match the characters the constitute the token INVERSEOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINVERSEOPENBRACKET(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INVERSEOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:22:20: ( 'inverse(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:22:22: 'inverse('
    {
        MATCHS(lit_10);
        if  (HASEXCEPTION())
        {
            goto ruleINVERSEOPENBRACKETEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleINVERSEOPENBRACKETEx; /* Prevent compiler warnings */
    ruleINVERSEOPENBRACKETEx: ;

}
// $ANTLR end INVERSEOPENBRACKET

//   Comes from: 23:13: ( '<-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LEFTPOINTER
 *
 * Looks to match the characters the constitute the token LEFTPOINTER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLEFTPOINTER(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LEFTPOINTER;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:23:13: ( '<-' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:23:15: '<-'
    {
        MATCHS(lit_11);
        if  (HASEXCEPTION())
        {
            goto ruleLEFTPOINTEREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLEFTPOINTEREx; /* Prevent compiler warnings */
    ruleLEFTPOINTEREx: ;

}
// $ANTLR end LEFTPOINTER

//   Comes from: 24:18: ( 'logit(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LOGITOPENBRACKET
 *
 * Looks to match the characters the constitute the token LOGITOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLOGITOPENBRACKET(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LOGITOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:24:18: ( 'logit(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:24:20: 'logit('
    {
        MATCHS(lit_12);
        if  (HASEXCEPTION())
        {
            goto ruleLOGITOPENBRACKETEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLOGITOPENBRACKETEx; /* Prevent compiler warnings */
    ruleLOGITOPENBRACKETEx: ;

}
// $ANTLR end LOGITOPENBRACKET

//   Comes from: 25:16: ( 'log(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LOGOPENBRACKET
 *
 * Looks to match the characters the constitute the token LOGOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLOGOPENBRACKET(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LOGOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:25:16: ( 'log(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:25:18: 'log('
    {
        MATCHS(lit_13);
        if  (HASEXCEPTION())
        {
            goto ruleLOGOPENBRACKETEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLOGOPENBRACKETEx; /* Prevent compiler warnings */
    ruleLOGOPENBRACKETEx: ;

}
// $ANTLR end LOGOPENBRACKET

//   Comes from: 26:7: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MINUS
 *
 * Looks to match the characters the constitute the token MINUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMINUS(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = MINUS;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:26:7: ( '-' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:26:9: '-'
    {
        MATCHC('-');
        if  (HASEXCEPTION())
        {
            goto ruleMINUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleMINUSEx; /* Prevent compiler warnings */
    ruleMINUSEx: ;

}
// $ANTLR end MINUS

//   Comes from: 27:7: ( 'model' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MODEL
 *
 * Looks to match the characters the constitute the token MODEL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMODEL(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = MODEL;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:27:7: ( 'model' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:27:9: 'model'
    {
        MATCHS(lit_14);
        if  (HASEXCEPTION())
        {
            goto ruleMODELEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleMODELEx; /* Prevent compiler warnings */
    ruleMODELEx: ;

}
// $ANTLR end MODEL

//   Comes from: 28:6: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MULT
 *
 * Looks to match the characters the constitute the token MULT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMULT(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = MULT;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:28:6: ( '*' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:28:8: '*'
    {
        MATCHC('*');
        if  (HASEXCEPTION())
        {
            goto ruleMULTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleMULTEx; /* Prevent compiler warnings */
    ruleMULTEx: ;

}
// $ANTLR end MULT

//   Comes from: 29:25: ( 'dmulti(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MUTLTINOMIALOPENBRACKET
 *
 * Looks to match the characters the constitute the token MUTLTINOMIALOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mMUTLTINOMIALOPENBRACKET(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = MUTLTINOMIALOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:29:25: ( 'dmulti(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:29:27: 'dmulti('
    {
        MATCHS(lit_15);
        if  (HASEXCEPTION())
        {
            goto ruleMUTLTINOMIALOPENBRACKETEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleMUTLTINOMIALOPENBRACKETEx; /* Prevent compiler warnings */
    ruleMUTLTINOMIALOPENBRACKETEx: ;

}
// $ANTLR end MUTLTINOMIALOPENBRACKET

//   Comes from: 30:11: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPENBRACE
 *
 * Looks to match the characters the constitute the token OPENBRACE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPENBRACE(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPENBRACE;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:30:11: ( '{' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:30:13: '{'
    {
        MATCHC('{');
        if  (HASEXCEPTION())
        {
            goto ruleOPENBRACEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPENBRACEEx; /* Prevent compiler warnings */
    ruleOPENBRACEEx: ;

}
// $ANTLR end OPENBRACE

//   Comes from: 31:13: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPENBRACKET
 *
 * Looks to match the characters the constitute the token OPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPENBRACKET(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:31:13: ( '(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:31:15: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto ruleOPENBRACKETEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPENBRACKETEx; /* Prevent compiler warnings */
    ruleOPENBRACKETEx: ;

}
// $ANTLR end OPENBRACKET

//   Comes from: 32:19: ( '[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPENSQUAREBRACKET
 *
 * Looks to match the characters the constitute the token OPENSQUAREBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPENSQUAREBRACKET(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPENSQUAREBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:32:19: ( '[' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:32:21: '['
    {
        MATCHC('[');
        if  (HASEXCEPTION())
        {
            goto ruleOPENSQUAREBRACKETEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPENSQUAREBRACKETEx; /* Prevent compiler warnings */
    ruleOPENSQUAREBRACKETEx: ;

}
// $ANTLR end OPENSQUAREBRACKET

//   Comes from: 33:6: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PLUS
 *
 * Looks to match the characters the constitute the token PLUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPLUS(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PLUS;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:33:6: ( '+' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:33:8: '+'
    {
        MATCHC('+');
        if  (HASEXCEPTION())
        {
            goto rulePLUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePLUSEx; /* Prevent compiler warnings */
    rulePLUSEx: ;

}
// $ANTLR end PLUS

//   Comes from: 34:19: ( 'probit(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PROBITOPENBRACKET
 *
 * Looks to match the characters the constitute the token PROBITOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPROBITOPENBRACKET(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PROBITOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:34:19: ( 'probit(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:34:21: 'probit('
    {
        MATCHS(lit_16);
        if  (HASEXCEPTION())
        {
            goto rulePROBITOPENBRACKETEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePROBITOPENBRACKETEx; /* Prevent compiler warnings */
    rulePROBITOPENBRACKETEx: ;

}
// $ANTLR end PROBITOPENBRACKET

//   Comes from: 35:7: ( '~' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start TILDE
 *
 * Looks to match the characters the constitute the token TILDE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mTILDE(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = TILDE;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:35:7: ( '~' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:35:9: '~'
    {
        MATCHC('~');
        if  (HASEXCEPTION())
        {
            goto ruleTILDEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleTILDEEx; /* Prevent compiler warnings */
    ruleTILDEEx: ;

}
// $ANTLR end TILDE

//   Comes from: 36:17: ( 'T(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start TRUNCATIONBEGIN
 *
 * Looks to match the characters the constitute the token TRUNCATIONBEGIN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mTRUNCATIONBEGIN(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = TRUNCATIONBEGIN;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:36:17: ( 'T(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:36:19: 'T('
    {
        MATCHS(lit_17);
        if  (HASEXCEPTION())
        {
            goto ruleTRUNCATIONBEGINEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleTRUNCATIONBEGINEx; /* Prevent compiler warnings */
    ruleTRUNCATIONBEGINEx: ;

}
// $ANTLR end TRUNCATIONBEGIN

//   Comes from: 44:2: ( ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CONSTANTINT
 *
 * Looks to match the characters the constitute the token CONSTANTINT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCONSTANTINT(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CONSTANTINT;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:44:2: ( ( '0' .. '9' )+ )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:44:4: ( '0' .. '9' )+
    {
        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:44:4: ( '0' .. '9' )+
        {
            int cnt1=0;

            for (;;)
            {
                int alt1=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt1=1;
        		}
        	    break;

        	}

        	switch (alt1)
        	{
        	    case 1:
        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleCONSTANTINTEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt1 >= 1 )
        		{
        		    goto loop1;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleCONSTANTINTEx;
        	}
        	cnt1++;
            }
            loop1: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCONSTANTINTEx; /* Prevent compiler warnings */
    ruleCONSTANTINTEx: ;

}
// $ANTLR end CONSTANTINT

//   Comes from: 48:2: ( ( 'a' .. 'z' | 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '.' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NODENAME
 *
 * Looks to match the characters the constitute the token NODENAME
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNODENAME(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NODENAME;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:48:2: ( ( 'a' .. 'z' | 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '.' )* )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:48:3: ( 'a' .. 'z' | 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '.' )*
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleNODENAMEEx;
        }


        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:48:24: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '.' )*

        for (;;)
        {
            int alt2=2;
            switch ( LA(1) )
            {
            case '.':
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt2=1;
            	}
                break;

            }

            switch (alt2)
            {
        	case 1:
        	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
        	    {
        	        if ( LA(1) == '.' || ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleNODENAMEEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop2;	/* break out of the loop */
        	    break;
            }
        }
        loop2: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNODENAMEEx; /* Prevent compiler warnings */
    ruleNODENAMEEx: ;

}
// $ANTLR end NODENAME

//   Comes from: 52:2: ( ( '+' | '-' )? ( '0' .. '9' )+ ( '.' ( '0' .. '9' )+ )? ( 'E' ( '+' | '-' )? ( '0' .. '9' )+ )? )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CONSTANTVALUE
 *
 * Looks to match the characters the constitute the token CONSTANTVALUE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCONSTANTVALUE(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CONSTANTVALUE;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:52:2: ( ( '+' | '-' )? ( '0' .. '9' )+ ( '.' ( '0' .. '9' )+ )? ( 'E' ( '+' | '-' )? ( '0' .. '9' )+ )? )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:52:4: ( '+' | '-' )? ( '0' .. '9' )+ ( '.' ( '0' .. '9' )+ )? ( 'E' ( '+' | '-' )? ( '0' .. '9' )+ )?
    {
        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:52:4: ( '+' | '-' )?
        {
            int alt3=2;
            switch ( LA(1) )
            {
                case '+':
                case '-':
                	{
                		alt3=1;
                	}
                    break;
            }

            switch (alt3)
            {
        	case 1:
        	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
        	    {
        	        if ( LA(1) == '+' || LA(1) == '-' )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleCONSTANTVALUEEx;
        	        }


        	    }
        	    break;

            }
        }

        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:52:14: ( '0' .. '9' )+
        {
            int cnt4=0;

            for (;;)
            {
                int alt4=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt4=1;
        		}
        	    break;

        	}

        	switch (alt4)
        	{
        	    case 1:
        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleCONSTANTVALUEEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt4 >= 1 )
        		{
        		    goto loop4;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleCONSTANTVALUEEx;
        	}
        	cnt4++;
            }
            loop4: ;	/* Jump to here if this rule does not match */
        }

        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:52:25: ( '.' ( '0' .. '9' )+ )?
        {
            int alt6=2;
            switch ( LA(1) )
            {
                case '.':
                	{
                		alt6=1;
                	}
                    break;
            }

            switch (alt6)
            {
        	case 1:
        	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:52:26: '.' ( '0' .. '9' )+
        	    {
        	        MATCHC('.');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleCONSTANTVALUEEx;
        	        }


        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:52:29: ( '0' .. '9' )+
        	        {
        	            int cnt5=0;

        	            for (;;)
        	            {
        	                int alt5=2;
        	        	switch ( LA(1) )
        	        	{
        	        	case '0':
        	        	case '1':
        	        	case '2':
        	        	case '3':
        	        	case '4':
        	        	case '5':
        	        	case '6':
        	        	case '7':
        	        	case '8':
        	        	case '9':
        	        		{
        	        			alt5=1;
        	        		}
        	        	    break;

        	        	}

        	        	switch (alt5)
        	        	{
        	        	    case 1:
        	        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
        	        	        {
        	        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	        	            {
        	        	                CONSUME();
        	        	            }
        	        	            else
        	        	            {
        	        	                CONSTRUCTEX();
        	        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	        	                LRECOVER();
        	        	                goto ruleCONSTANTVALUEEx;
        	        	            }


        	        	        }
        	        	        break;

        	        	    default:

        	        		if ( cnt5 >= 1 )
        	        		{
        	        		    goto loop5;
        	        		}
        	        		/* mismatchedSetEx()
        	        		 */
        	        		CONSTRUCTEX();
        	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        	        		goto ruleCONSTANTVALUEEx;
        	        	}
        	        	cnt5++;
        	            }
        	            loop5: ;	/* Jump to here if this rule does not match */
        	        }

        	    }
        	    break;

            }
        }

        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:52:42: ( 'E' ( '+' | '-' )? ( '0' .. '9' )+ )?
        {
            int alt9=2;
            switch ( LA(1) )
            {
                case 'E':
                	{
                		alt9=1;
                	}
                    break;
            }

            switch (alt9)
            {
        	case 1:
        	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:52:43: 'E' ( '+' | '-' )? ( '0' .. '9' )+
        	    {
        	        MATCHC('E');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleCONSTANTVALUEEx;
        	        }


        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:52:46: ( '+' | '-' )?
        	        {
        	            int alt7=2;
        	            switch ( LA(1) )
        	            {
        	                case '+':
        	                case '-':
        	                	{
        	                		alt7=1;
        	                	}
        	                    break;
        	            }

        	            switch (alt7)
        	            {
        	        	case 1:
        	        	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
        	        	    {
        	        	        if ( LA(1) == '+' || LA(1) == '-' )
        	        	        {
        	        	            CONSUME();
        	        	        }
        	        	        else
        	        	        {
        	        	            CONSTRUCTEX();
        	        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	        	            LRECOVER();
        	        	            goto ruleCONSTANTVALUEEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:52:56: ( '0' .. '9' )+
        	        {
        	            int cnt8=0;

        	            for (;;)
        	            {
        	                int alt8=2;
        	        	switch ( LA(1) )
        	        	{
        	        	case '0':
        	        	case '1':
        	        	case '2':
        	        	case '3':
        	        	case '4':
        	        	case '5':
        	        	case '6':
        	        	case '7':
        	        	case '8':
        	        	case '9':
        	        		{
        	        			alt8=1;
        	        		}
        	        	    break;

        	        	}

        	        	switch (alt8)
        	        	{
        	        	    case 1:
        	        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
        	        	        {
        	        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	        	            {
        	        	                CONSUME();
        	        	            }
        	        	            else
        	        	            {
        	        	                CONSTRUCTEX();
        	        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	        	                LRECOVER();
        	        	                goto ruleCONSTANTVALUEEx;
        	        	            }


        	        	        }
        	        	        break;

        	        	    default:

        	        		if ( cnt8 >= 1 )
        	        		{
        	        		    goto loop8;
        	        		}
        	        		/* mismatchedSetEx()
        	        		 */
        	        		CONSTRUCTEX();
        	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        	        		goto ruleCONSTANTVALUEEx;
        	        	}
        	        	cnt8++;
        	            }
        	            loop8: ;	/* Jump to here if this rule does not match */
        	        }

        	    }
        	    break;

            }
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCONSTANTVALUEEx; /* Prevent compiler warnings */
    ruleCONSTANTVALUEEx: ;

}
// $ANTLR end CONSTANTVALUE

//   Comes from: 55:12: ( ( '\\t' | ' ' | '\\r' | '\\n' | ';' | '\\u000C' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WHITESPACE
 *
 * Looks to match the characters the constitute the token WHITESPACE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWHITESPACE(pBUGSLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WHITESPACE;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:55:12: ( ( '\\t' | ' ' | '\\r' | '\\n' | ';' | '\\u000C' )+ )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:55:14: ( '\\t' | ' ' | '\\r' | '\\n' | ';' | '\\u000C' )+
    {
        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:55:14: ( '\\t' | ' ' | '\\r' | '\\n' | ';' | '\\u000C' )+
        {
            int cnt10=0;

            for (;;)
            {
                int alt10=2;
        	switch ( LA(1) )
        	{
        	case '\t':
        	case '\n':
        	case '\f':
        	case '\r':
        	case ' ':
        	case ';':
        		{
        			alt10=1;
        		}
        	    break;

        	}

        	switch (alt10)
        	{
        	    case 1:
        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || ((LA(1) >= '\f') && (LA(1) <= '\r')) || LA(1) == ' ' || LA(1) == ';' )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleWHITESPACEEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt10 >= 1 )
        		{
        		    goto loop10;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWHITESPACEEx;
        	}
        	cnt10++;
            }
            loop10: ;	/* Jump to here if this rule does not match */
        }

        {
             LEXSTATE->channel = HIDDEN; 
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWHITESPACEEx; /* Prevent compiler warnings */
    ruleWHITESPACEEx: ;

}
// $ANTLR end WHITESPACE

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pBUGSLexer ctx)
{
    {
        //  /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:8: ( ABSOPENBRACKET | BERNOULLIOPENBRACKET | BETAOPENBRACKET | CENSORBEGINWITHC | CENSORBEGINWITHI | CLOGLOGOPENBRACKET | CLOSEBRACE | CLOSEBRACKET | CLOSESQUAREBRACKET | COLON | COMMA | DIRICHLETOPENBRACKET | DIV | FORSTART | IN | INVERSEOPENBRACKET | LEFTPOINTER | LOGITOPENBRACKET | LOGOPENBRACKET | MINUS | MODEL | MULT | MUTLTINOMIALOPENBRACKET | OPENBRACE | OPENBRACKET | OPENSQUAREBRACKET | PLUS | PROBITOPENBRACKET | TILDE | TRUNCATIONBEGIN | CONSTANTINT | NODENAME | CONSTANTVALUE | WHITESPACE )

        ANTLR3_UINT32 alt11;

        alt11=34;

        alt11 = cdfa11.predict(ctx, RECOGNIZER, ISTREAM, &cdfa11);
        if  (HASEXCEPTION())
        {
            goto ruleTokensEx;
        }

        switch (alt11)
        {
    	case 1:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:10: ABSOPENBRACKET
    	    {
    	        /* 1:10: ABSOPENBRACKET */
    	        mABSOPENBRACKET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:25: BERNOULLIOPENBRACKET
    	    {
    	        /* 1:25: BERNOULLIOPENBRACKET */
    	        mBERNOULLIOPENBRACKET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:46: BETAOPENBRACKET
    	    {
    	        /* 1:46: BETAOPENBRACKET */
    	        mBETAOPENBRACKET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:62: CENSORBEGINWITHC
    	    {
    	        /* 1:62: CENSORBEGINWITHC */
    	        mCENSORBEGINWITHC(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:79: CENSORBEGINWITHI
    	    {
    	        /* 1:79: CENSORBEGINWITHI */
    	        mCENSORBEGINWITHI(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:96: CLOGLOGOPENBRACKET
    	    {
    	        /* 1:96: CLOGLOGOPENBRACKET */
    	        mCLOGLOGOPENBRACKET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:115: CLOSEBRACE
    	    {
    	        /* 1:115: CLOSEBRACE */
    	        mCLOSEBRACE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:126: CLOSEBRACKET
    	    {
    	        /* 1:126: CLOSEBRACKET */
    	        mCLOSEBRACKET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:139: CLOSESQUAREBRACKET
    	    {
    	        /* 1:139: CLOSESQUAREBRACKET */
    	        mCLOSESQUAREBRACKET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:158: COLON
    	    {
    	        /* 1:158: COLON */
    	        mCOLON(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:164: COMMA
    	    {
    	        /* 1:164: COMMA */
    	        mCOMMA(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:170: DIRICHLETOPENBRACKET
    	    {
    	        /* 1:170: DIRICHLETOPENBRACKET */
    	        mDIRICHLETOPENBRACKET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:191: DIV
    	    {
    	        /* 1:191: DIV */
    	        mDIV(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:195: FORSTART
    	    {
    	        /* 1:195: FORSTART */
    	        mFORSTART(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:204: IN
    	    {
    	        /* 1:204: IN */
    	        mIN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:207: INVERSEOPENBRACKET
    	    {
    	        /* 1:207: INVERSEOPENBRACKET */
    	        mINVERSEOPENBRACKET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:226: LEFTPOINTER
    	    {
    	        /* 1:226: LEFTPOINTER */
    	        mLEFTPOINTER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:238: LOGITOPENBRACKET
    	    {
    	        /* 1:238: LOGITOPENBRACKET */
    	        mLOGITOPENBRACKET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:255: LOGOPENBRACKET
    	    {
    	        /* 1:255: LOGOPENBRACKET */
    	        mLOGOPENBRACKET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:270: MINUS
    	    {
    	        /* 1:270: MINUS */
    	        mMINUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:276: MODEL
    	    {
    	        /* 1:276: MODEL */
    	        mMODEL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:282: MULT
    	    {
    	        /* 1:282: MULT */
    	        mMULT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:287: MUTLTINOMIALOPENBRACKET
    	    {
    	        /* 1:287: MUTLTINOMIALOPENBRACKET */
    	        mMUTLTINOMIALOPENBRACKET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:311: OPENBRACE
    	    {
    	        /* 1:311: OPENBRACE */
    	        mOPENBRACE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 25:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:321: OPENBRACKET
    	    {
    	        /* 1:321: OPENBRACKET */
    	        mOPENBRACKET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 26:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:333: OPENSQUAREBRACKET
    	    {
    	        /* 1:333: OPENSQUAREBRACKET */
    	        mOPENSQUAREBRACKET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 27:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:351: PLUS
    	    {
    	        /* 1:351: PLUS */
    	        mPLUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 28:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:356: PROBITOPENBRACKET
    	    {
    	        /* 1:356: PROBITOPENBRACKET */
    	        mPROBITOPENBRACKET(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 29:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:374: TILDE
    	    {
    	        /* 1:374: TILDE */
    	        mTILDE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 30:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:380: TRUNCATIONBEGIN
    	    {
    	        /* 1:380: TRUNCATIONBEGIN */
    	        mTRUNCATIONBEGIN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 31:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:396: CONSTANTINT
    	    {
    	        /* 1:396: CONSTANTINT */
    	        mCONSTANTINT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 32:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:408: NODENAME
    	    {
    	        /* 1:408: NODENAME */
    	        mNODENAME(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 33:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:417: CONSTANTVALUE
    	    {
    	        /* 1:417: CONSTANTVALUE */
    	        mCONSTANTVALUE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 34:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:431: WHITESPACE
    	    {
    	        /* 1:431: WHITESPACE */
    	        mWHITESPACE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
