/** \file
 *  This C++ source file was generated by $ANTLR version 3.5-rc-2
 *
 *     -  From the grammar source file : /u/s/h/shrirams/bugsparser/Parser/BUGS.g
 *     -                            On : 2013-01-15 17:10:48
 *     -                 for the lexer : BUGSLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C++ language generator and runtime by Gokulakannan Somasundaram ( heavy lifting from C Run-time by Jim Idle )
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Gokulakannan Somasundaram, ElectronDB
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "BUGSLexer.hpp"
/* ----------------------------------------- */



	namespace BUGS {


/** String literals used by BUGSLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR_UCHAR	lit_1[]  = { 0x61, 0x62, 0x73, 0x28,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_2[]  = { 0x64, 0x62, 0x65, 0x72, 0x6E, 0x28,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_3[]  = { 0x64, 0x62, 0x65, 0x74, 0x61, 0x28,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_4[]  = { 0x64, 0x62, 0x69, 0x6E, 0x28,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_5[]  = { 0x43, 0x28,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_6[]  = { 0x49, 0x28,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_7[]  = { 0x63, 0x6C, 0x6F, 0x67, 0x6C, 0x6F, 0x67, 0x28,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_8[]  = { 0x64, 0x64, 0x69, 0x72, 0x69, 0x63, 0x68, 0x28,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_9[]  = { 0x66, 0x6F, 0x72,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_10[]  = { 0x69, 0x6E,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_11[]  = { 0x69, 0x6E, 0x76, 0x65, 0x72, 0x73, 0x65, 0x28,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_12[]  = { 0x3C, 0x2D,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_13[]  = { 0x6C, 0x6F, 0x67, 0x69, 0x74, 0x28,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_14[]  = { 0x6C, 0x6F, 0x67, 0x28,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_15[]  = { 0x6D, 0x6F, 0x64, 0x65, 0x6C,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_16[]  = { 0x64, 0x6D, 0x75, 0x6C, 0x74, 0x69, 0x28,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_17[]  = { 0x70, 0x72, 0x6F, 0x62, 0x69, 0x74, 0x28,  antlr3::ANTLR_STRING_TERMINATOR};
static ANTLR_UCHAR	lit_18[]  = { 0x54, 0x28,  antlr3::ANTLR_STRING_TERMINATOR};

	}



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

using namespace antlr3;

	namespace BUGS {


/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



BUGSLexer::~BUGSLexer()
{
}

void
BUGSLexer::reset()
{
    this->get_rec()->reset();
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/u/s/h/shrirams/bugsparser/Parser/BUGS.g";

/** \brief Return the name of the grammar file that generated this code.
 */
const char* BUGSLexer::getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called BUGSLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pBUGSLexer initialized for the lex start
 *     - Fail NULL
 */
BUGSLexer::BUGSLexer(StreamType* instream)
:BUGSLexerImplTraits::BaseLexerType(ANTLR_SIZE_HINT, instream, NULL)
{
	// See if we can create a new lexer with the standard constructor
	//
	this->init(instream );
}

/** \brief Create a new lexer called BUGSLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pBUGSLexer initialized for the lex start
 *     - Fail NULL
 */
BUGSLexer::BUGSLexer(StreamType* instream, RecognizerSharedStateType* state)
:BUGSLexerImplTraits::BaseLexerType(ANTLR_SIZE_HINT, instream, state)
{
	this->init(instream );
}

void BUGSLexer::init(StreamType* instream)
{
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in BUGSLexer.h here so you can get a sense
     * of what goes where.
     */

}


/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( ABSOPENBRACKET | BERNOULLIOPENBRACKET | BETAOPENBRACKET | BINOMIALOPENBRACKET | CENSORBEGINWITHC | CENSORBEGINWITHI | CLOGLOGOPENBRACKET | CLOSEBRACE | CLOSEBRACKET | CLOSESQUAREBRACKET | COLON | COMMA | DIRICHLETOPENBRACKET | DIV | DOT | EQUALTO | FORSTART | IN | INVERSEOPENBRACKET | LEFTPOINTER | LOGITOPENBRACKET | LOGOPENBRACKET | MINUS | MODEL | MULT | MUTLTINOMIALOPENBRACKET | OPENBRACE | OPENBRACKET | OPENSQUAREBRACKET | PLUS | PROBITOPENBRACKET | TILDE | TRUNCATIONBEGIN | CONSTANTINT | NODENAME | CONSTANTVALUE | WHITESPACE );
 */
static const ANTLR_INT32 dfa17_eot[99] =
    {
	-1, 29, 29, 29, 29, 29, -1, -1, -1, -1, -1, -1, -1, -1, 29, 29, -1, 29, 
	-1, 29, -1, -1, 42, -1, -1, 29, -1, 29, 46, -1, -1, 29, 29, 29, 29, -1, 
	-1, 29, 29, 55, 29, 29, -1, -1, 29, -1, -1, 29, 29, 29, 29, 29, 29, 66, 
	29, -1, 29, 29, 29, -1, 29, 29, 29, 29, 29, 29, -1, 29, 29, -1, 29, 29, 
	29, 29, -1, 29, 29, 29, 29, 29, 89, 29, -1, -1, 29, 29, 29, 29, -1, -1, 
	29, 29, -1, 29, 29, -1, -1, -1, -1
    };
static const ANTLR_INT32 dfa17_eof[99] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR_INT32 dfa17_min[99] =
    {
	9, 98, 98, 40, 40, 108, -1, -1, -1, -1, -1, -1, -1, -1, 111, 110, -1, 111, 
	-1, 111, -1, -1, 43, -1, -1, 114, -1, 40, 46, -1, -1, 115, 101, 105, 117, 
	-1, -1, 111, 114, 46, 103, 100, -1, -1, 111, -1, -1, 40, 114, 110, 114, 
	108, 103, 46, 101, -1, 40, 101, 98, -1, 110, 97, 40, 105, 116, 108, -1, 
	114, 116, -1, 108, 105, 40, 40, -1, 99, 105, 111, 115, 40, 46, 116, -1, 
	-1, 104, 40, 103, 101, -1, -1, 40, 40, -1, 40, 40, -1, -1, -1, -1
    };
static const ANTLR_INT32 dfa17_max[99] =
    {
	126, 98, 109, 40, 40, 108, -1, -1, -1, -1, -1, -1, -1, -1, 111, 110, -1, 
	111, -1, 111, -1, -1, 45, -1, -1, 114, -1, 40, 69, -1, -1, 115, 105, 105, 
	117, -1, -1, 111, 114, 122, 103, 100, -1, -1, 111, -1, -1, 40, 116, 110, 
	114, 108, 103, 122, 101, -1, 105, 101, 98, -1, 110, 97, 40, 105, 116, 108, 
	-1, 114, 116, -1, 108, 105, 40, 40, -1, 99, 105, 111, 115, 40, 122, 116, 
	-1, -1, 104, 40, 103, 101, -1, -1, 40, 40, -1, 40, 40, -1, -1, -1, -1
    };
static const ANTLR_INT32 dfa17_accept[99] =
    {
	-1, -1, -1, -1, -1, -1, 8, 9, 10, 11, 12, 14, 15, 16, -1, -1, 20, -1, 23, 
	-1, 25, 27, -1, 29, 30, -1, 32, -1, -1, 35, 37, -1, -1, -1, -1, 5, 6, -1, 
	-1, -1, -1, -1, 28, 36, -1, 33, 34, -1, -1, -1, -1, -1, -1, -1, -1, 18, 
	-1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 17, -1, -1, 22, -1, -1, -1, -1, 
	4, -1, -1, -1, -1, -1, -1, -1, 2, 3, -1, -1, -1, -1, 21, 24, -1, -1, 26, 
	-1, -1, 31, 13, 7, 19
    };
static const ANTLR_INT32 dfa17_special[99] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
static const ANTLR_INT32* dfa17_T_empty	 =   NULL;

static const ANTLR_INT32 dfa17_T0[] =
    {
	67
    };

static const ANTLR_INT32 dfa17_T1[] =
    {
	98
    };

static const ANTLR_INT32 dfa17_T2[] =
    {
	94
    };

static const ANTLR_INT32 dfa17_T3[] =
    {
	87
    };

static const ANTLR_INT32 dfa17_T4[] =
    {
	78
    };

static const ANTLR_INT32 dfa17_T5[] =
    {
	60, -1, 61
    };

static const ANTLR_INT32 dfa17_T6[] =
    {
	79
    };

static const ANTLR_INT32 dfa17_T7[] =
    {
	88
    };

static const ANTLR_INT32 dfa17_T8[] =
    {
	30, 30, -1, 30, 30, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 30, -1, -1, -1, -1, -1, -1, -1, 22, 7, 20, 24, 10, 
	18, 12, 11, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 9, 30, 16, 13, -1, 
	-1, -1, 29, 29, 3, 29, 29, 29, 29, 29, 4, 29, 29, 29, 29, 29, 29, 29, 29, 
	29, 29, 27, 29, 29, 29, 29, 29, 29, 23, -1, 8, -1, -1, -1, 1, 29, 5, 2, 
	29, 14, 29, 29, 15, 29, 29, 17, 19, 29, 29, 25, 29, 29, 29, 29, 29, 29, 
	29, 29, 29, 29, 21, -1, 6, 26
    };

static const ANTLR_INT32 dfa17_T9[] =
    {
	37
    };

static const ANTLR_INT32 dfa17_T10[] =
    {
	70
    };

static const ANTLR_INT32 dfa17_T11[] =
    {
	57
    };

static const ANTLR_INT32 dfa17_T12[] =
    {
	36
    };

static const ANTLR_INT32 dfa17_T13[] =
    {
	35
    };

static const ANTLR_INT32 dfa17_T14[] =
    {
	51
    };

static const ANTLR_INT32 dfa17_T15[] =
    {
	64
    };

static const ANTLR_INT32 dfa17_T16[] =
    {
	76
    };

static const ANTLR_INT32 dfa17_T17[] =
    {
	85
    };

static const ANTLR_INT32 dfa17_T18[] =
    {
	92
    };

static const ANTLR_INT32 dfa17_T19[] =
    {
	80
    };

static const ANTLR_INT32 dfa17_T20[] =
    {
	39
    };

static const ANTLR_INT32 dfa17_T21[] =
    {
	43, -1, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 43
    };

static const ANTLR_INT32 dfa17_T22[] =
    {
	95
    };

static const ANTLR_INT32 dfa17_T23[] =
    {
	41
    };

static const ANTLR_INT32 dfa17_T24[] =
    {
	81
    };

static const ANTLR_INT32 dfa17_T25[] =
    {
	90
    };

static const ANTLR_INT32 dfa17_T26[] =
    {
	58
    };

static const ANTLR_INT32 dfa17_T27[] =
    {
	71
    };

static const ANTLR_INT32 dfa17_T28[] =
    {
	48, -1, -1, -1, 49
    };

static const ANTLR_INT32 dfa17_T29[] =
    {
	29, -1, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, -1, -1, -1, -1, -1, -1, 
	-1, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 
	29, 29, 29, 29, 29, 29, 29, 29, 29, -1, -1, -1, -1, -1, -1, 29, 29, 29, 
	29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 
	29, 29, 29, 29, 29
    };

static const ANTLR_INT32 dfa17_T30[] =
    {
	38
    };

static const ANTLR_INT32 dfa17_T31[] =
    {
	32, -1, 33, -1, -1, -1, -1, -1, -1, -1, -1, 34
    };

static const ANTLR_INT32 dfa17_T32[] =
    {
	40
    };

static const ANTLR_INT32 dfa17_T33[] =
    {
	59
    };

static const ANTLR_INT32 dfa17_T34[] =
    {
	47
    };

static const ANTLR_INT32 dfa17_T35[] =
    {
	72
    };

static const ANTLR_INT32 dfa17_T36[] =
    {
	82
    };

static const ANTLR_INT32 dfa17_T37[] =
    {
	83
    };

static const ANTLR_INT32 dfa17_T38[] =
    {
	73
    };

static const ANTLR_INT32 dfa17_T39[] =
    {
	74
    };

static const ANTLR_INT32 dfa17_T40[] =
    {
	62
    };

static const ANTLR_INT32 dfa17_T41[] =
    {
	31
    };

static const ANTLR_INT32 dfa17_T42[] =
    {
	69, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 68
    };

static const ANTLR_INT32 dfa17_T43[] =
    {
	97
    };

static const ANTLR_INT32 dfa17_T44[] =
    {
	86
    };

static const ANTLR_INT32 dfa17_T45[] =
    {
	93
    };

static const ANTLR_INT32 dfa17_T46[] =
    {
	65
    };

static const ANTLR_INT32 dfa17_T47[] =
    {
	77
    };

static const ANTLR_INT32 dfa17_T48[] =
    {
	52
    };

static const ANTLR_INT32 dfa17_T49[] =
    {
	44
    };

static const ANTLR_INT32 dfa17_T50[] =
    {
	43, -1, 43
    };

static const ANTLR_INT32 dfa17_T51[] =
    {
	56
    };

static const ANTLR_INT32 dfa17_T52[] =
    {
	91
    };

static const ANTLR_INT32 dfa17_T53[] =
    {
	96
    };

static const ANTLR_INT32 dfa17_T54[] =
    {
	50
    };

static const ANTLR_INT32 dfa17_T55[] =
    {
	63
    };

static const ANTLR_INT32 dfa17_T56[] =
    {
	75
    };

static const ANTLR_INT32 dfa17_T57[] =
    {
	84
    };

static const ANTLR_INT32 dfa17_T58[] =
    {
	53
    };

static const ANTLR_INT32 dfa17_T59[] =
    {
	45
    };

static const ANTLR_INT32 dfa17_T60[] =
    {
	29, -1, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, -1, -1, -1, -1, -1, -1, 
	-1, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 
	29, 29, 29, 29, 29, 29, 29, 29, 29, -1, -1, -1, -1, -1, -1, 29, 29, 29, 
	29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 
	54, 29, 29, 29, 29
    };


/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR_INT32 * const dfa17_transitions[] =
{
    dfa17_T8, dfa17_T41, dfa17_T31, dfa17_T13, dfa17_T12, dfa17_T9, NULL, 
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, dfa17_T30, dfa17_T20, NULL, 
    dfa17_T32, NULL, dfa17_T23, NULL, NULL, dfa17_T50, NULL, NULL, dfa17_T49, 
    NULL, dfa17_T59, dfa17_T21, NULL, NULL, dfa17_T34, dfa17_T28, dfa17_T54, 
    dfa17_T14, NULL, NULL, dfa17_T48, dfa17_T58, dfa17_T60, dfa17_T51, dfa17_T11, 
    NULL, NULL, dfa17_T26, NULL, NULL, dfa17_T33, dfa17_T5, dfa17_T40, dfa17_T55, 
    dfa17_T15, dfa17_T46, dfa17_T29, dfa17_T0, NULL, dfa17_T42, dfa17_T10, 
    dfa17_T27, NULL, dfa17_T35, dfa17_T38, dfa17_T39, dfa17_T56, dfa17_T16, 
    dfa17_T47, NULL, dfa17_T4, dfa17_T6, NULL, dfa17_T19, dfa17_T24, dfa17_T36, 
    dfa17_T37, NULL, dfa17_T57, dfa17_T17, dfa17_T44, dfa17_T3, dfa17_T7, 
    dfa17_T29, dfa17_T25, NULL, NULL, dfa17_T52, dfa17_T18, dfa17_T45, dfa17_T2, 
    NULL, NULL, dfa17_T22, dfa17_T53, NULL, dfa17_T43, dfa17_T1, NULL, NULL, 
    NULL, NULL
};


/* Declare tracking structure for Cyclic DFA 17
 */
class BUGSLexerCyclicDFA17 : public CyclicDFA< BUGSLexerImplTraits, BUGSLexer >, public BUGSLexerTokens
{
public:
	typedef CyclicDFA< BUGSLexerImplTraits, BUGSLexer >  BaseType;
	typedef BaseType::ContextType CtxType;

private:
	

public:
	BUGSLexerCyclicDFA17( ANTLR_INT32	decisionNumber
					, const ANTLR_UCHAR*	description
					, const ANTLR_INT32* const	eot
					, const ANTLR_INT32* const	eof
					, const ANTLR_INT32* const	min
					, const ANTLR_INT32* const	max
					, const ANTLR_INT32* const	accept
					, const ANTLR_INT32* const	special
					, const ANTLR_INT32* const *const	transition)
					:BaseType( decisionNumber, description, eot, eof, min, max, accept,
								special, transition )
	{
		
	}

};

static BUGSLexerCyclicDFA17  cdfa17(
	    17,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const ANTLR_UCHAR*)"1:1: Tokens : ( ABSOPENBRACKET | BERNOULLIOPENBRACKET | BETAOPENBRACKET | BINOMIALOPENBRACKET | CENSORBEGINWITHC | CENSORBEGINWITHI | CLOGLOGOPENBRACKET | CLOSEBRACE | CLOSEBRACKET | CLOSESQUAREBRACKET | COLON | COMMA | DIRICHLETOPENBRACKET | DIV | DOT | EQUALTO | FORSTART | IN | INVERSEOPENBRACKET | LEFTPOINTER | LOGITOPENBRACKET | LOGOPENBRACKET | MINUS | MODEL | MULT | MUTLTINOMIALOPENBRACKET | OPENBRACE | OPENBRACKET | OPENSQUAREBRACKET | PLUS | PROBITOPENBRACKET | TILDE | TRUNCATIONBEGIN | CONSTANTINT | NODENAME | CONSTANTVALUE | WHITESPACE );",
	    dfa17_eot,	    /* EOT table			    */
	    dfa17_eof,	    /* EOF table			    */
	    dfa17_min,	    /* Minimum tokens for each state    */
	    dfa17_max,	    /* Maximum tokens for each state    */
	    dfa17_accept,	/* Accept table			    */
	    dfa17_special,	/* Special transition states	    */
	    dfa17_transitions	/* Table of transition tables	    */

	);


/* End of Cyclic DFA 17
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 22:16: ( 'abs(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ABSOPENBRACKET
 *
 * Looks to match the characters the constitute the token ABSOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mABSOPENBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = ABSOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:22:16: ( 'abs(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:22:18: 'abs('
    {
        this->matchs(lit_1);
        if  (this->hasException())
        {
            goto ruleABSOPENBRACKETEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleABSOPENBRACKETEx; /* Prevent compiler warnings */
    ruleABSOPENBRACKETEx: ;

}
// $ANTLR end ABSOPENBRACKET

//   Comes from: 23:22: ( 'dbern(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BERNOULLIOPENBRACKET
 *
 * Looks to match the characters the constitute the token BERNOULLIOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mBERNOULLIOPENBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = BERNOULLIOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:23:22: ( 'dbern(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:23:24: 'dbern('
    {
        this->matchs(lit_2);
        if  (this->hasException())
        {
            goto ruleBERNOULLIOPENBRACKETEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleBERNOULLIOPENBRACKETEx; /* Prevent compiler warnings */
    ruleBERNOULLIOPENBRACKETEx: ;

}
// $ANTLR end BERNOULLIOPENBRACKET

//   Comes from: 24:17: ( 'dbeta(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BETAOPENBRACKET
 *
 * Looks to match the characters the constitute the token BETAOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mBETAOPENBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = BETAOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:24:17: ( 'dbeta(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:24:19: 'dbeta('
    {
        this->matchs(lit_3);
        if  (this->hasException())
        {
            goto ruleBETAOPENBRACKETEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleBETAOPENBRACKETEx; /* Prevent compiler warnings */
    ruleBETAOPENBRACKETEx: ;

}
// $ANTLR end BETAOPENBRACKET

//   Comes from: 25:21: ( 'dbin(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start BINOMIALOPENBRACKET
 *
 * Looks to match the characters the constitute the token BINOMIALOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mBINOMIALOPENBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = BINOMIALOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:25:21: ( 'dbin(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:25:23: 'dbin('
    {
        this->matchs(lit_4);
        if  (this->hasException())
        {
            goto ruleBINOMIALOPENBRACKETEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleBINOMIALOPENBRACKETEx; /* Prevent compiler warnings */
    ruleBINOMIALOPENBRACKETEx: ;

}
// $ANTLR end BINOMIALOPENBRACKET

//   Comes from: 26:18: ( 'C(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CENSORBEGINWITHC
 *
 * Looks to match the characters the constitute the token CENSORBEGINWITHC
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mCENSORBEGINWITHC()
{
    ANTLR_UINT32	_type;
      


    _type	    = CENSORBEGINWITHC;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:26:18: ( 'C(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:26:20: 'C('
    {
        this->matchs(lit_5);
        if  (this->hasException())
        {
            goto ruleCENSORBEGINWITHCEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleCENSORBEGINWITHCEx; /* Prevent compiler warnings */
    ruleCENSORBEGINWITHCEx: ;

}
// $ANTLR end CENSORBEGINWITHC

//   Comes from: 27:18: ( 'I(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CENSORBEGINWITHI
 *
 * Looks to match the characters the constitute the token CENSORBEGINWITHI
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mCENSORBEGINWITHI()
{
    ANTLR_UINT32	_type;
      


    _type	    = CENSORBEGINWITHI;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:27:18: ( 'I(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:27:20: 'I('
    {
        this->matchs(lit_6);
        if  (this->hasException())
        {
            goto ruleCENSORBEGINWITHIEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleCENSORBEGINWITHIEx; /* Prevent compiler warnings */
    ruleCENSORBEGINWITHIEx: ;

}
// $ANTLR end CENSORBEGINWITHI

//   Comes from: 28:20: ( 'cloglog(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CLOGLOGOPENBRACKET
 *
 * Looks to match the characters the constitute the token CLOGLOGOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mCLOGLOGOPENBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = CLOGLOGOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:28:20: ( 'cloglog(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:28:22: 'cloglog('
    {
        this->matchs(lit_7);
        if  (this->hasException())
        {
            goto ruleCLOGLOGOPENBRACKETEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleCLOGLOGOPENBRACKETEx; /* Prevent compiler warnings */
    ruleCLOGLOGOPENBRACKETEx: ;

}
// $ANTLR end CLOGLOGOPENBRACKET

//   Comes from: 29:12: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CLOSEBRACE
 *
 * Looks to match the characters the constitute the token CLOSEBRACE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mCLOSEBRACE()
{
    ANTLR_UINT32	_type;
      


    _type	    = CLOSEBRACE;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:29:12: ( '}' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:29:14: '}'
    {
         this->matchc('}');
        if  (this->hasException())
        {
            goto ruleCLOSEBRACEEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleCLOSEBRACEEx; /* Prevent compiler warnings */
    ruleCLOSEBRACEEx: ;

}
// $ANTLR end CLOSEBRACE

//   Comes from: 30:14: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CLOSEBRACKET
 *
 * Looks to match the characters the constitute the token CLOSEBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mCLOSEBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = CLOSEBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:30:14: ( ')' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:30:16: ')'
    {
         this->matchc(')');
        if  (this->hasException())
        {
            goto ruleCLOSEBRACKETEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleCLOSEBRACKETEx; /* Prevent compiler warnings */
    ruleCLOSEBRACKETEx: ;

}
// $ANTLR end CLOSEBRACKET

//   Comes from: 31:20: ( ']' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CLOSESQUAREBRACKET
 *
 * Looks to match the characters the constitute the token CLOSESQUAREBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mCLOSESQUAREBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = CLOSESQUAREBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:31:20: ( ']' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:31:22: ']'
    {
         this->matchc(']');
        if  (this->hasException())
        {
            goto ruleCLOSESQUAREBRACKETEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleCLOSESQUAREBRACKETEx; /* Prevent compiler warnings */
    ruleCLOSESQUAREBRACKETEx: ;

}
// $ANTLR end CLOSESQUAREBRACKET

//   Comes from: 32:7: ( ':' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COLON
 *
 * Looks to match the characters the constitute the token COLON
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mCOLON()
{
    ANTLR_UINT32	_type;
      


    _type	    = COLON;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:32:7: ( ':' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:32:9: ':'
    {
         this->matchc(':');
        if  (this->hasException())
        {
            goto ruleCOLONEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleCOLONEx; /* Prevent compiler warnings */
    ruleCOLONEx: ;

}
// $ANTLR end COLON

//   Comes from: 33:7: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMA
 *
 * Looks to match the characters the constitute the token COMMA
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mCOMMA()
{
    ANTLR_UINT32	_type;
      


    _type	    = COMMA;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:33:7: ( ',' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:33:9: ','
    {
         this->matchc(',');
        if  (this->hasException())
        {
            goto ruleCOMMAEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleCOMMAEx; /* Prevent compiler warnings */
    ruleCOMMAEx: ;

}
// $ANTLR end COMMA

//   Comes from: 34:22: ( 'ddirich(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DIRICHLETOPENBRACKET
 *
 * Looks to match the characters the constitute the token DIRICHLETOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mDIRICHLETOPENBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = DIRICHLETOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:34:22: ( 'ddirich(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:34:24: 'ddirich('
    {
        this->matchs(lit_8);
        if  (this->hasException())
        {
            goto ruleDIRICHLETOPENBRACKETEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleDIRICHLETOPENBRACKETEx; /* Prevent compiler warnings */
    ruleDIRICHLETOPENBRACKETEx: ;

}
// $ANTLR end DIRICHLETOPENBRACKET

//   Comes from: 35:5: ( '/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DIV
 *
 * Looks to match the characters the constitute the token DIV
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mDIV()
{
    ANTLR_UINT32	_type;
      


    _type	    = DIV;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:35:5: ( '/' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:35:7: '/'
    {
         this->matchc('/');
        if  (this->hasException())
        {
            goto ruleDIVEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleDIVEx; /* Prevent compiler warnings */
    ruleDIVEx: ;

}
// $ANTLR end DIV

//   Comes from: 36:5: ( '.' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DOT
 *
 * Looks to match the characters the constitute the token DOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mDOT()
{
    ANTLR_UINT32	_type;
      


    _type	    = DOT;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:36:5: ( '.' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:36:7: '.'
    {
         this->matchc('.');
        if  (this->hasException())
        {
            goto ruleDOTEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleDOTEx; /* Prevent compiler warnings */
    ruleDOTEx: ;

}
// $ANTLR end DOT

//   Comes from: 37:9: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EQUALTO
 *
 * Looks to match the characters the constitute the token EQUALTO
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mEQUALTO()
{
    ANTLR_UINT32	_type;
      


    _type	    = EQUALTO;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:37:9: ( '=' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:37:11: '='
    {
         this->matchc('=');
        if  (this->hasException())
        {
            goto ruleEQUALTOEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleEQUALTOEx; /* Prevent compiler warnings */
    ruleEQUALTOEx: ;

}
// $ANTLR end EQUALTO

//   Comes from: 38:10: ( 'for' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start FORSTART
 *
 * Looks to match the characters the constitute the token FORSTART
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mFORSTART()
{
    ANTLR_UINT32	_type;
      


    _type	    = FORSTART;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:38:10: ( 'for' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:38:12: 'for'
    {
        this->matchs(lit_9);
        if  (this->hasException())
        {
            goto ruleFORSTARTEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleFORSTARTEx; /* Prevent compiler warnings */
    ruleFORSTARTEx: ;

}
// $ANTLR end FORSTART

//   Comes from: 39:4: ( 'in' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start IN
 *
 * Looks to match the characters the constitute the token IN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mIN()
{
    ANTLR_UINT32	_type;
      


    _type	    = IN;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:39:4: ( 'in' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:39:6: 'in'
    {
        this->matchs(lit_10);
        if  (this->hasException())
        {
            goto ruleINEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleINEx; /* Prevent compiler warnings */
    ruleINEx: ;

}
// $ANTLR end IN

//   Comes from: 40:20: ( 'inverse(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INVERSEOPENBRACKET
 *
 * Looks to match the characters the constitute the token INVERSEOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mINVERSEOPENBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = INVERSEOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:40:20: ( 'inverse(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:40:22: 'inverse('
    {
        this->matchs(lit_11);
        if  (this->hasException())
        {
            goto ruleINVERSEOPENBRACKETEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleINVERSEOPENBRACKETEx; /* Prevent compiler warnings */
    ruleINVERSEOPENBRACKETEx: ;

}
// $ANTLR end INVERSEOPENBRACKET

//   Comes from: 41:13: ( '<-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LEFTPOINTER
 *
 * Looks to match the characters the constitute the token LEFTPOINTER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mLEFTPOINTER()
{
    ANTLR_UINT32	_type;
      


    _type	    = LEFTPOINTER;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:41:13: ( '<-' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:41:15: '<-'
    {
        this->matchs(lit_12);
        if  (this->hasException())
        {
            goto ruleLEFTPOINTEREx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleLEFTPOINTEREx; /* Prevent compiler warnings */
    ruleLEFTPOINTEREx: ;

}
// $ANTLR end LEFTPOINTER

//   Comes from: 42:18: ( 'logit(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LOGITOPENBRACKET
 *
 * Looks to match the characters the constitute the token LOGITOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mLOGITOPENBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = LOGITOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:42:18: ( 'logit(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:42:20: 'logit('
    {
        this->matchs(lit_13);
        if  (this->hasException())
        {
            goto ruleLOGITOPENBRACKETEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleLOGITOPENBRACKETEx; /* Prevent compiler warnings */
    ruleLOGITOPENBRACKETEx: ;

}
// $ANTLR end LOGITOPENBRACKET

//   Comes from: 43:16: ( 'log(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LOGOPENBRACKET
 *
 * Looks to match the characters the constitute the token LOGOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mLOGOPENBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = LOGOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:43:16: ( 'log(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:43:18: 'log('
    {
        this->matchs(lit_14);
        if  (this->hasException())
        {
            goto ruleLOGOPENBRACKETEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleLOGOPENBRACKETEx; /* Prevent compiler warnings */
    ruleLOGOPENBRACKETEx: ;

}
// $ANTLR end LOGOPENBRACKET

//   Comes from: 44:7: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MINUS
 *
 * Looks to match the characters the constitute the token MINUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mMINUS()
{
    ANTLR_UINT32	_type;
      


    _type	    = MINUS;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:44:7: ( '-' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:44:9: '-'
    {
         this->matchc('-');
        if  (this->hasException())
        {
            goto ruleMINUSEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleMINUSEx; /* Prevent compiler warnings */
    ruleMINUSEx: ;

}
// $ANTLR end MINUS

//   Comes from: 45:7: ( 'model' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MODEL
 *
 * Looks to match the characters the constitute the token MODEL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mMODEL()
{
    ANTLR_UINT32	_type;
      


    _type	    = MODEL;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:45:7: ( 'model' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:45:9: 'model'
    {
        this->matchs(lit_15);
        if  (this->hasException())
        {
            goto ruleMODELEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleMODELEx; /* Prevent compiler warnings */
    ruleMODELEx: ;

}
// $ANTLR end MODEL

//   Comes from: 46:6: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MULT
 *
 * Looks to match the characters the constitute the token MULT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mMULT()
{
    ANTLR_UINT32	_type;
      


    _type	    = MULT;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:46:6: ( '*' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:46:8: '*'
    {
         this->matchc('*');
        if  (this->hasException())
        {
            goto ruleMULTEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleMULTEx; /* Prevent compiler warnings */
    ruleMULTEx: ;

}
// $ANTLR end MULT

//   Comes from: 47:25: ( 'dmulti(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start MUTLTINOMIALOPENBRACKET
 *
 * Looks to match the characters the constitute the token MUTLTINOMIALOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mMUTLTINOMIALOPENBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = MUTLTINOMIALOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:47:25: ( 'dmulti(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:47:27: 'dmulti('
    {
        this->matchs(lit_16);
        if  (this->hasException())
        {
            goto ruleMUTLTINOMIALOPENBRACKETEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleMUTLTINOMIALOPENBRACKETEx; /* Prevent compiler warnings */
    ruleMUTLTINOMIALOPENBRACKETEx: ;

}
// $ANTLR end MUTLTINOMIALOPENBRACKET

//   Comes from: 48:11: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPENBRACE
 *
 * Looks to match the characters the constitute the token OPENBRACE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mOPENBRACE()
{
    ANTLR_UINT32	_type;
      


    _type	    = OPENBRACE;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:48:11: ( '{' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:48:13: '{'
    {
         this->matchc('{');
        if  (this->hasException())
        {
            goto ruleOPENBRACEEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleOPENBRACEEx; /* Prevent compiler warnings */
    ruleOPENBRACEEx: ;

}
// $ANTLR end OPENBRACE

//   Comes from: 49:13: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPENBRACKET
 *
 * Looks to match the characters the constitute the token OPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mOPENBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = OPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:49:13: ( '(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:49:15: '('
    {
         this->matchc('(');
        if  (this->hasException())
        {
            goto ruleOPENBRACKETEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleOPENBRACKETEx; /* Prevent compiler warnings */
    ruleOPENBRACKETEx: ;

}
// $ANTLR end OPENBRACKET

//   Comes from: 50:19: ( '[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPENSQUAREBRACKET
 *
 * Looks to match the characters the constitute the token OPENSQUAREBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mOPENSQUAREBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = OPENSQUAREBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:50:19: ( '[' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:50:21: '['
    {
         this->matchc('[');
        if  (this->hasException())
        {
            goto ruleOPENSQUAREBRACKETEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleOPENSQUAREBRACKETEx; /* Prevent compiler warnings */
    ruleOPENSQUAREBRACKETEx: ;

}
// $ANTLR end OPENSQUAREBRACKET

//   Comes from: 51:6: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PLUS
 *
 * Looks to match the characters the constitute the token PLUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mPLUS()
{
    ANTLR_UINT32	_type;
      


    _type	    = PLUS;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:51:6: ( '+' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:51:8: '+'
    {
         this->matchc('+');
        if  (this->hasException())
        {
            goto rulePLUSEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto rulePLUSEx; /* Prevent compiler warnings */
    rulePLUSEx: ;

}
// $ANTLR end PLUS

//   Comes from: 52:19: ( 'probit(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PROBITOPENBRACKET
 *
 * Looks to match the characters the constitute the token PROBITOPENBRACKET
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mPROBITOPENBRACKET()
{
    ANTLR_UINT32	_type;
      


    _type	    = PROBITOPENBRACKET;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:52:19: ( 'probit(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:52:21: 'probit('
    {
        this->matchs(lit_17);
        if  (this->hasException())
        {
            goto rulePROBITOPENBRACKETEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto rulePROBITOPENBRACKETEx; /* Prevent compiler warnings */
    rulePROBITOPENBRACKETEx: ;

}
// $ANTLR end PROBITOPENBRACKET

//   Comes from: 53:7: ( '~' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start TILDE
 *
 * Looks to match the characters the constitute the token TILDE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mTILDE()
{
    ANTLR_UINT32	_type;
      


    _type	    = TILDE;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:53:7: ( '~' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:53:9: '~'
    {
         this->matchc('~');
        if  (this->hasException())
        {
            goto ruleTILDEEx;
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleTILDEEx; /* Prevent compiler warnings */
    ruleTILDEEx: ;

}
// $ANTLR end TILDE

//   Comes from: 54:17: ( 'T(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start TRUNCATIONBEGIN
 *
 * Looks to match the characters the constitute the token TRUNCATIONBEGIN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mTRUNCATIONBEGIN()
{
    ANTLR_UINT32	_type;
      


    _type	    = TRUNCATIONBEGIN;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:54:17: ( 'T(' )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:54:19: 'T('
    {
        this->matchs(lit_18);
        if  (this->hasException())
        {
            goto ruleTRUNCATIONBEGINEx;
        }




    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleTRUNCATIONBEGINEx; /* Prevent compiler warnings */
    ruleTRUNCATIONBEGINEx: ;

}
// $ANTLR end TRUNCATIONBEGIN

//   Comes from: 266:2: ( ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CONSTANTINT
 *
 * Looks to match the characters the constitute the token CONSTANTINT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mCONSTANTINT()
{
    ANTLR_UINT32	_type;
      


    _type	    = CONSTANTINT;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:266:2: ( ( '0' .. '9' )+ )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:266:4: ( '0' .. '9' )+
    {
        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:266:4: ( '0' .. '9' )+
        {
            int cnt1=0;

            for (;;)
            {
                int alt1=2;
        	switch ( this->LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt1=1;
        		}
        	    break;

        	}

        	switch (alt1)
        	{
        	    case 1:
        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
        	        {
        	            if ( ((this->LA(1) >= '0') && (this->LA(1) <= '9')) )
        	            {
        	                this->consume();
        	            }
        	            else
        	            {
        	                new ANTLR_Exception< BUGSLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

        	                this->recover();
        	                goto ruleCONSTANTINTEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt1 >= 1 )
        		{
        		    goto loop1;
        		}
        		/* mismatchedSetEx()
        		 */
        		new ANTLR_Exception< BUGSLexerImplTraits, EARLY_EXIT_EXCEPTION, StreamType>( this->get_rec(), "" );


        		goto ruleCONSTANTINTEx;
        	}
        	cnt1++;
            }
            loop1: ;	/* Jump to here if this rule does not match */
        }

    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleCONSTANTINTEx; /* Prevent compiler warnings */
    ruleCONSTANTINTEx: ;

}
// $ANTLR end CONSTANTINT

//   Comes from: 270:2: ( ( 'a' .. 'z' | 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '.' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NODENAME
 *
 * Looks to match the characters the constitute the token NODENAME
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mNODENAME()
{
    ANTLR_UINT32	_type;
      


    _type	    = NODENAME;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:270:2: ( ( 'a' .. 'z' | 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '.' )* )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:270:3: ( 'a' .. 'z' | 'A' .. 'Z' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '.' )*
    {
        if ( ((this->LA(1) >= 'A') && (this->LA(1) <= 'Z')) || ((this->LA(1) >= 'a') && (this->LA(1) <= 'z')) )
        {
            this->consume();
        }
        else
        {
            new ANTLR_Exception< BUGSLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

            this->recover();
            goto ruleNODENAMEEx;
        }


        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:270:24: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '.' )*

        for (;;)
        {
            int alt2=2;
            switch ( this->LA(1) )
            {
            case '.':
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt2=1;
            	}
                break;

            }

            switch (alt2)
            {
        	case 1:
        	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
        	    {
        	        if ( this->LA(1) == '.' || ((this->LA(1) >= '0') && (this->LA(1) <= '9')) || ((this->LA(1) >= 'A') && (this->LA(1) <= 'Z')) || ((this->LA(1) >= 'a') && (this->LA(1) <= 'z')) )
        	        {
        	            this->consume();
        	        }
        	        else
        	        {
        	            new ANTLR_Exception< BUGSLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

        	            this->recover();
        	            goto ruleNODENAMEEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop2;	/* break out of the loop */
        	    break;
            }
        }
        loop2: ; /* Jump out to here if this rule does not match */


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleNODENAMEEx; /* Prevent compiler warnings */
    ruleNODENAMEEx: ;

}
// $ANTLR end NODENAME

//   Comes from: 274:2: ( ( '0' .. '9' )+ ( DOT ( '0' .. '9' )+ )? ( 'E' ( PLUS | MINUS )? ( '0' .. '9' )+ )? | OPENBRACKET ( PLUS | MINUS ) ( '0' .. '9' )+ CLOSEBRACKET ( DOT ( '0' .. '9' )+ )? ( 'E' ( PLUS | MINUS )? ( '0' .. '9' )+ )? )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CONSTANTVALUE
 *
 * Looks to match the characters the constitute the token CONSTANTVALUE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mCONSTANTVALUE()
{
    ANTLR_UINT32	_type;
      


    _type	    = CONSTANTVALUE;


    {
        //  /u/s/h/shrirams/bugsparser/Parser/BUGS.g:274:2: ( ( '0' .. '9' )+ ( DOT ( '0' .. '9' )+ )? ( 'E' ( PLUS | MINUS )? ( '0' .. '9' )+ )? | OPENBRACKET ( PLUS | MINUS ) ( '0' .. '9' )+ CLOSEBRACKET ( DOT ( '0' .. '9' )+ )? ( 'E' ( PLUS | MINUS )? ( '0' .. '9' )+ )? )

        ANTLR_UINT32 alt15;

        alt15=2;

        switch ( this->LA(1) )
        {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt15=1;
        	}
            break;
        case '(':
        	{
        		alt15=2;
        	}
            break;

        default:
            ExceptionBaseType* ex = new ANTLR_Exception< BUGSLexerImplTraits, NO_VIABLE_ALT_EXCEPTION, StreamType>( this->get_rec(), "" );
            ex->set_decisionNum( 15 );
            ex->set_state( 0 );


            goto ruleCONSTANTVALUEEx;

        }

        switch (alt15)
        {
    	case 1:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:274:4: ( '0' .. '9' )+ ( DOT ( '0' .. '9' )+ )? ( 'E' ( PLUS | MINUS )? ( '0' .. '9' )+ )?
    	    {
    	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:274:4: ( '0' .. '9' )+
    	        {
    	            int cnt3=0;

    	            for (;;)
    	            {
    	                int alt3=2;
    	        	switch ( this->LA(1) )
    	        	{
    	        	case '0':
    	        	case '1':
    	        	case '2':
    	        	case '3':
    	        	case '4':
    	        	case '5':
    	        	case '6':
    	        	case '7':
    	        	case '8':
    	        	case '9':
    	        		{
    	        			alt3=1;
    	        		}
    	        	    break;

    	        	}

    	        	switch (alt3)
    	        	{
    	        	    case 1:
    	        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
    	        	        {
    	        	            if ( ((this->LA(1) >= '0') && (this->LA(1) <= '9')) )
    	        	            {
    	        	                this->consume();
    	        	            }
    	        	            else
    	        	            {
    	        	                new ANTLR_Exception< BUGSLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

    	        	                this->recover();
    	        	                goto ruleCONSTANTVALUEEx;
    	        	            }


    	        	        }
    	        	        break;

    	        	    default:

    	        		if ( cnt3 >= 1 )
    	        		{
    	        		    goto loop3;
    	        		}
    	        		/* mismatchedSetEx()
    	        		 */
    	        		new ANTLR_Exception< BUGSLexerImplTraits, EARLY_EXIT_EXCEPTION, StreamType>( this->get_rec(), "" );


    	        		goto ruleCONSTANTVALUEEx;
    	        	}
    	        	cnt3++;
    	            }
    	            loop3: ;	/* Jump to here if this rule does not match */
    	        }

    	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:274:15: ( DOT ( '0' .. '9' )+ )?
    	        {
    	            int alt5=2;
    	            switch ( this->LA(1) )
    	            {
    	                case '.':
    	                	{
    	                		alt5=1;
    	                	}
    	                    break;
    	            }

    	            switch (alt5)
    	            {
    	        	case 1:
    	        	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:274:16: DOT ( '0' .. '9' )+
    	        	    {
    	        	        /* 274:16: DOT ( '0' .. '9' )+ */
    	        	        mDOT();
    	        	        if  (this->hasException())
    	        	        {
    	        	            goto ruleCONSTANTVALUEEx;
    	        	        }



    	        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:274:19: ( '0' .. '9' )+
    	        	        {
    	        	            int cnt4=0;

    	        	            for (;;)
    	        	            {
    	        	                int alt4=2;
    	        	        	switch ( this->LA(1) )
    	        	        	{
    	        	        	case '0':
    	        	        	case '1':
    	        	        	case '2':
    	        	        	case '3':
    	        	        	case '4':
    	        	        	case '5':
    	        	        	case '6':
    	        	        	case '7':
    	        	        	case '8':
    	        	        	case '9':
    	        	        		{
    	        	        			alt4=1;
    	        	        		}
    	        	        	    break;

    	        	        	}

    	        	        	switch (alt4)
    	        	        	{
    	        	        	    case 1:
    	        	        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
    	        	        	        {
    	        	        	            if ( ((this->LA(1) >= '0') && (this->LA(1) <= '9')) )
    	        	        	            {
    	        	        	                this->consume();
    	        	        	            }
    	        	        	            else
    	        	        	            {
    	        	        	                new ANTLR_Exception< BUGSLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

    	        	        	                this->recover();
    	        	        	                goto ruleCONSTANTVALUEEx;
    	        	        	            }


    	        	        	        }
    	        	        	        break;

    	        	        	    default:

    	        	        		if ( cnt4 >= 1 )
    	        	        		{
    	        	        		    goto loop4;
    	        	        		}
    	        	        		/* mismatchedSetEx()
    	        	        		 */
    	        	        		new ANTLR_Exception< BUGSLexerImplTraits, EARLY_EXIT_EXCEPTION, StreamType>( this->get_rec(), "" );


    	        	        		goto ruleCONSTANTVALUEEx;
    	        	        	}
    	        	        	cnt4++;
    	        	            }
    	        	            loop4: ;	/* Jump to here if this rule does not match */
    	        	        }

    	        	    }
    	        	    break;

    	            }
    	        }

    	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:274:32: ( 'E' ( PLUS | MINUS )? ( '0' .. '9' )+ )?
    	        {
    	            int alt8=2;
    	            switch ( this->LA(1) )
    	            {
    	                case 'E':
    	                	{
    	                		alt8=1;
    	                	}
    	                    break;
    	            }

    	            switch (alt8)
    	            {
    	        	case 1:
    	        	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:274:33: 'E' ( PLUS | MINUS )? ( '0' .. '9' )+
    	        	    {
    	        	         this->matchc('E');
    	        	        if  (this->hasException())
    	        	        {
    	        	            goto ruleCONSTANTVALUEEx;
    	        	        }


    	        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:274:36: ( PLUS | MINUS )?
    	        	        {
    	        	            int alt6=2;
    	        	            switch ( this->LA(1) )
    	        	            {
    	        	                case '+':
    	        	                case '-':
    	        	                	{
    	        	                		alt6=1;
    	        	                	}
    	        	                    break;
    	        	            }

    	        	            switch (alt6)
    	        	            {
    	        	        	case 1:
    	        	        	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
    	        	        	    {
    	        	        	        if ( this->LA(1) == '+' || this->LA(1) == '-' )
    	        	        	        {
    	        	        	            this->consume();
    	        	        	        }
    	        	        	        else
    	        	        	        {
    	        	        	            new ANTLR_Exception< BUGSLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

    	        	        	            this->recover();
    	        	        	            goto ruleCONSTANTVALUEEx;
    	        	        	        }


    	        	        	    }
    	        	        	    break;

    	        	            }
    	        	        }

    	        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:274:49: ( '0' .. '9' )+
    	        	        {
    	        	            int cnt7=0;

    	        	            for (;;)
    	        	            {
    	        	                int alt7=2;
    	        	        	switch ( this->LA(1) )
    	        	        	{
    	        	        	case '0':
    	        	        	case '1':
    	        	        	case '2':
    	        	        	case '3':
    	        	        	case '4':
    	        	        	case '5':
    	        	        	case '6':
    	        	        	case '7':
    	        	        	case '8':
    	        	        	case '9':
    	        	        		{
    	        	        			alt7=1;
    	        	        		}
    	        	        	    break;

    	        	        	}

    	        	        	switch (alt7)
    	        	        	{
    	        	        	    case 1:
    	        	        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
    	        	        	        {
    	        	        	            if ( ((this->LA(1) >= '0') && (this->LA(1) <= '9')) )
    	        	        	            {
    	        	        	                this->consume();
    	        	        	            }
    	        	        	            else
    	        	        	            {
    	        	        	                new ANTLR_Exception< BUGSLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

    	        	        	                this->recover();
    	        	        	                goto ruleCONSTANTVALUEEx;
    	        	        	            }


    	        	        	        }
    	        	        	        break;

    	        	        	    default:

    	        	        		if ( cnt7 >= 1 )
    	        	        		{
    	        	        		    goto loop7;
    	        	        		}
    	        	        		/* mismatchedSetEx()
    	        	        		 */
    	        	        		new ANTLR_Exception< BUGSLexerImplTraits, EARLY_EXIT_EXCEPTION, StreamType>( this->get_rec(), "" );


    	        	        		goto ruleCONSTANTVALUEEx;
    	        	        	}
    	        	        	cnt7++;
    	        	            }
    	        	            loop7: ;	/* Jump to here if this rule does not match */
    	        	        }

    	        	    }
    	        	    break;

    	            }
    	        }

    	    }
    	    break;
    	case 2:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:275:4: OPENBRACKET ( PLUS | MINUS ) ( '0' .. '9' )+ CLOSEBRACKET ( DOT ( '0' .. '9' )+ )? ( 'E' ( PLUS | MINUS )? ( '0' .. '9' )+ )?
    	    {
    	        /* 275:4: OPENBRACKET ( PLUS | MINUS ) ( '0' .. '9' )+ CLOSEBRACKET ( DOT ( '0' .. '9' )+ )? ( 'E' ( PLUS | MINUS )? ( '0' .. '9' )+ )? */
    	        mOPENBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleCONSTANTVALUEEx;
    	        }



    	        if ( this->LA(1) == '+' || this->LA(1) == '-' )
    	        {
    	            this->consume();
    	        }
    	        else
    	        {
    	            new ANTLR_Exception< BUGSLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

    	            this->recover();
    	            goto ruleCONSTANTVALUEEx;
    	        }


    	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:275:29: ( '0' .. '9' )+
    	        {
    	            int cnt9=0;

    	            for (;;)
    	            {
    	                int alt9=2;
    	        	switch ( this->LA(1) )
    	        	{
    	        	case '0':
    	        	case '1':
    	        	case '2':
    	        	case '3':
    	        	case '4':
    	        	case '5':
    	        	case '6':
    	        	case '7':
    	        	case '8':
    	        	case '9':
    	        		{
    	        			alt9=1;
    	        		}
    	        	    break;

    	        	}

    	        	switch (alt9)
    	        	{
    	        	    case 1:
    	        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
    	        	        {
    	        	            if ( ((this->LA(1) >= '0') && (this->LA(1) <= '9')) )
    	        	            {
    	        	                this->consume();
    	        	            }
    	        	            else
    	        	            {
    	        	                new ANTLR_Exception< BUGSLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

    	        	                this->recover();
    	        	                goto ruleCONSTANTVALUEEx;
    	        	            }


    	        	        }
    	        	        break;

    	        	    default:

    	        		if ( cnt9 >= 1 )
    	        		{
    	        		    goto loop9;
    	        		}
    	        		/* mismatchedSetEx()
    	        		 */
    	        		new ANTLR_Exception< BUGSLexerImplTraits, EARLY_EXIT_EXCEPTION, StreamType>( this->get_rec(), "" );


    	        		goto ruleCONSTANTVALUEEx;
    	        	}
    	        	cnt9++;
    	            }
    	            loop9: ;	/* Jump to here if this rule does not match */
    	        }

    	        /* 275:4: OPENBRACKET ( PLUS | MINUS ) ( '0' .. '9' )+ CLOSEBRACKET ( DOT ( '0' .. '9' )+ )? ( 'E' ( PLUS | MINUS )? ( '0' .. '9' )+ )? */
    	        mCLOSEBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleCONSTANTVALUEEx;
    	        }



    	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:275:54: ( DOT ( '0' .. '9' )+ )?
    	        {
    	            int alt11=2;
    	            switch ( this->LA(1) )
    	            {
    	                case '.':
    	                	{
    	                		alt11=1;
    	                	}
    	                    break;
    	            }

    	            switch (alt11)
    	            {
    	        	case 1:
    	        	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:275:55: DOT ( '0' .. '9' )+
    	        	    {
    	        	        /* 275:55: DOT ( '0' .. '9' )+ */
    	        	        mDOT();
    	        	        if  (this->hasException())
    	        	        {
    	        	            goto ruleCONSTANTVALUEEx;
    	        	        }



    	        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:275:58: ( '0' .. '9' )+
    	        	        {
    	        	            int cnt10=0;

    	        	            for (;;)
    	        	            {
    	        	                int alt10=2;
    	        	        	switch ( this->LA(1) )
    	        	        	{
    	        	        	case '0':
    	        	        	case '1':
    	        	        	case '2':
    	        	        	case '3':
    	        	        	case '4':
    	        	        	case '5':
    	        	        	case '6':
    	        	        	case '7':
    	        	        	case '8':
    	        	        	case '9':
    	        	        		{
    	        	        			alt10=1;
    	        	        		}
    	        	        	    break;

    	        	        	}

    	        	        	switch (alt10)
    	        	        	{
    	        	        	    case 1:
    	        	        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
    	        	        	        {
    	        	        	            if ( ((this->LA(1) >= '0') && (this->LA(1) <= '9')) )
    	        	        	            {
    	        	        	                this->consume();
    	        	        	            }
    	        	        	            else
    	        	        	            {
    	        	        	                new ANTLR_Exception< BUGSLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

    	        	        	                this->recover();
    	        	        	                goto ruleCONSTANTVALUEEx;
    	        	        	            }


    	        	        	        }
    	        	        	        break;

    	        	        	    default:

    	        	        		if ( cnt10 >= 1 )
    	        	        		{
    	        	        		    goto loop10;
    	        	        		}
    	        	        		/* mismatchedSetEx()
    	        	        		 */
    	        	        		new ANTLR_Exception< BUGSLexerImplTraits, EARLY_EXIT_EXCEPTION, StreamType>( this->get_rec(), "" );


    	        	        		goto ruleCONSTANTVALUEEx;
    	        	        	}
    	        	        	cnt10++;
    	        	            }
    	        	            loop10: ;	/* Jump to here if this rule does not match */
    	        	        }

    	        	    }
    	        	    break;

    	            }
    	        }

    	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:275:71: ( 'E' ( PLUS | MINUS )? ( '0' .. '9' )+ )?
    	        {
    	            int alt14=2;
    	            switch ( this->LA(1) )
    	            {
    	                case 'E':
    	                	{
    	                		alt14=1;
    	                	}
    	                    break;
    	            }

    	            switch (alt14)
    	            {
    	        	case 1:
    	        	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:275:72: 'E' ( PLUS | MINUS )? ( '0' .. '9' )+
    	        	    {
    	        	         this->matchc('E');
    	        	        if  (this->hasException())
    	        	        {
    	        	            goto ruleCONSTANTVALUEEx;
    	        	        }


    	        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:275:75: ( PLUS | MINUS )?
    	        	        {
    	        	            int alt12=2;
    	        	            switch ( this->LA(1) )
    	        	            {
    	        	                case '+':
    	        	                case '-':
    	        	                	{
    	        	                		alt12=1;
    	        	                	}
    	        	                    break;
    	        	            }

    	        	            switch (alt12)
    	        	            {
    	        	        	case 1:
    	        	        	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
    	        	        	    {
    	        	        	        if ( this->LA(1) == '+' || this->LA(1) == '-' )
    	        	        	        {
    	        	        	            this->consume();
    	        	        	        }
    	        	        	        else
    	        	        	        {
    	        	        	            new ANTLR_Exception< BUGSLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

    	        	        	            this->recover();
    	        	        	            goto ruleCONSTANTVALUEEx;
    	        	        	        }


    	        	        	    }
    	        	        	    break;

    	        	            }
    	        	        }

    	        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:275:88: ( '0' .. '9' )+
    	        	        {
    	        	            int cnt13=0;

    	        	            for (;;)
    	        	            {
    	        	                int alt13=2;
    	        	        	switch ( this->LA(1) )
    	        	        	{
    	        	        	case '0':
    	        	        	case '1':
    	        	        	case '2':
    	        	        	case '3':
    	        	        	case '4':
    	        	        	case '5':
    	        	        	case '6':
    	        	        	case '7':
    	        	        	case '8':
    	        	        	case '9':
    	        	        		{
    	        	        			alt13=1;
    	        	        		}
    	        	        	    break;

    	        	        	}

    	        	        	switch (alt13)
    	        	        	{
    	        	        	    case 1:
    	        	        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
    	        	        	        {
    	        	        	            if ( ((this->LA(1) >= '0') && (this->LA(1) <= '9')) )
    	        	        	            {
    	        	        	                this->consume();
    	        	        	            }
    	        	        	            else
    	        	        	            {
    	        	        	                new ANTLR_Exception< BUGSLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

    	        	        	                this->recover();
    	        	        	                goto ruleCONSTANTVALUEEx;
    	        	        	            }


    	        	        	        }
    	        	        	        break;

    	        	        	    default:

    	        	        		if ( cnt13 >= 1 )
    	        	        		{
    	        	        		    goto loop13;
    	        	        		}
    	        	        		/* mismatchedSetEx()
    	        	        		 */
    	        	        		new ANTLR_Exception< BUGSLexerImplTraits, EARLY_EXIT_EXCEPTION, StreamType>( this->get_rec(), "" );


    	        	        		goto ruleCONSTANTVALUEEx;
    	        	        	}
    	        	        	cnt13++;
    	        	            }
    	        	            loop13: ;	/* Jump to here if this rule does not match */
    	        	        }

    	        	    }
    	        	    break;

    	            }
    	        }

    	    }
    	    break;

        }
    }
	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleCONSTANTVALUEEx; /* Prevent compiler warnings */
    ruleCONSTANTVALUEEx: ;

}
// $ANTLR end CONSTANTVALUE

//   Comes from: 278:12: ( ( '\\t' | ' ' | '\\r' | '\\n' | ';' | '\\u000C' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WHITESPACE
 *
 * Looks to match the characters the constitute the token WHITESPACE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == true if an exception was thrown.
 */
void BUGSLexer::mWHITESPACE()
{
    ANTLR_UINT32	_type;
      


    _type	    = WHITESPACE;


    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:278:12: ( ( '\\t' | ' ' | '\\r' | '\\n' | ';' | '\\u000C' )+ )
    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:278:14: ( '\\t' | ' ' | '\\r' | '\\n' | ';' | '\\u000C' )+
    {
        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:278:14: ( '\\t' | ' ' | '\\r' | '\\n' | ';' | '\\u000C' )+
        {
            int cnt16=0;

            for (;;)
            {
                int alt16=2;
        	switch ( this->LA(1) )
        	{
        	case '\t':
        	case '\n':
        	case '\f':
        	case '\r':
        	case ' ':
        	case ';':
        		{
        			alt16=1;
        		}
        	    break;

        	}

        	switch (alt16)
        	{
        	    case 1:
        	        // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:
        	        {
        	            if ( ((this->LA(1) >= '\t') && (this->LA(1) <= '\n')) || ((this->LA(1) >= '\f') && (this->LA(1) <= '\r')) || this->LA(1) == ' ' || this->LA(1) == ';' )
        	            {
        	                this->consume();
        	            }
        	            else
        	            {
        	                new ANTLR_Exception< BUGSLexerImplTraits, MISMATCHED_SET_EXCEPTION, StreamType>( this->get_rec(), "" );

        	                this->recover();
        	                goto ruleWHITESPACEEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt16 >= 1 )
        		{
        		    goto loop16;
        		}
        		/* mismatchedSetEx()
        		 */
        		new ANTLR_Exception< BUGSLexerImplTraits, EARLY_EXIT_EXCEPTION, StreamType>( this->get_rec(), "" );


        		goto ruleWHITESPACEEx;
        	}
        	cnt16++;
            }
            loop16: ;	/* Jump to here if this rule does not match */
        }

        {
             this->get_state()->get_channel() = HIDDEN; skip();
        }


    }

	this->get_lexstate()->set_type(_type);
    // This is where rules clean up and exit
    //
    goto ruleWHITESPACEEx; /* Prevent compiler warnings */
    ruleWHITESPACEEx: ;

}
// $ANTLR end WHITESPACE

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
void
BUGSLexer::mTokens()
{
    {
        //  /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:8: ( ABSOPENBRACKET | BERNOULLIOPENBRACKET | BETAOPENBRACKET | BINOMIALOPENBRACKET | CENSORBEGINWITHC | CENSORBEGINWITHI | CLOGLOGOPENBRACKET | CLOSEBRACE | CLOSEBRACKET | CLOSESQUAREBRACKET | COLON | COMMA | DIRICHLETOPENBRACKET | DIV | DOT | EQUALTO | FORSTART | IN | INVERSEOPENBRACKET | LEFTPOINTER | LOGITOPENBRACKET | LOGOPENBRACKET | MINUS | MODEL | MULT | MUTLTINOMIALOPENBRACKET | OPENBRACE | OPENBRACKET | OPENSQUAREBRACKET | PLUS | PROBITOPENBRACKET | TILDE | TRUNCATIONBEGIN | CONSTANTINT | NODENAME | CONSTANTVALUE | WHITESPACE )

        ANTLR_UINT32 alt17;

        alt17=37;

        alt17 = cdfa17.predict(this, this->get_rec(), this->get_istream(), cdfa17 );
        if  (this->hasException())
        {
            goto ruleTokensEx;
        }

        switch (alt17)
        {
    	case 1:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:10: ABSOPENBRACKET
    	    {
    	        /* 1:10: ABSOPENBRACKET */
    	        mABSOPENBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:25: BERNOULLIOPENBRACKET
    	    {
    	        /* 1:25: BERNOULLIOPENBRACKET */
    	        mBERNOULLIOPENBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:46: BETAOPENBRACKET
    	    {
    	        /* 1:46: BETAOPENBRACKET */
    	        mBETAOPENBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:62: BINOMIALOPENBRACKET
    	    {
    	        /* 1:62: BINOMIALOPENBRACKET */
    	        mBINOMIALOPENBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:82: CENSORBEGINWITHC
    	    {
    	        /* 1:82: CENSORBEGINWITHC */
    	        mCENSORBEGINWITHC();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:99: CENSORBEGINWITHI
    	    {
    	        /* 1:99: CENSORBEGINWITHI */
    	        mCENSORBEGINWITHI();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:116: CLOGLOGOPENBRACKET
    	    {
    	        /* 1:116: CLOGLOGOPENBRACKET */
    	        mCLOGLOGOPENBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:135: CLOSEBRACE
    	    {
    	        /* 1:135: CLOSEBRACE */
    	        mCLOSEBRACE();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:146: CLOSEBRACKET
    	    {
    	        /* 1:146: CLOSEBRACKET */
    	        mCLOSEBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:159: CLOSESQUAREBRACKET
    	    {
    	        /* 1:159: CLOSESQUAREBRACKET */
    	        mCLOSESQUAREBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:178: COLON
    	    {
    	        /* 1:178: COLON */
    	        mCOLON();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:184: COMMA
    	    {
    	        /* 1:184: COMMA */
    	        mCOMMA();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:190: DIRICHLETOPENBRACKET
    	    {
    	        /* 1:190: DIRICHLETOPENBRACKET */
    	        mDIRICHLETOPENBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:211: DIV
    	    {
    	        /* 1:211: DIV */
    	        mDIV();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:215: DOT
    	    {
    	        /* 1:215: DOT */
    	        mDOT();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:219: EQUALTO
    	    {
    	        /* 1:219: EQUALTO */
    	        mEQUALTO();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:227: FORSTART
    	    {
    	        /* 1:227: FORSTART */
    	        mFORSTART();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:236: IN
    	    {
    	        /* 1:236: IN */
    	        mIN();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:239: INVERSEOPENBRACKET
    	    {
    	        /* 1:239: INVERSEOPENBRACKET */
    	        mINVERSEOPENBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:258: LEFTPOINTER
    	    {
    	        /* 1:258: LEFTPOINTER */
    	        mLEFTPOINTER();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:270: LOGITOPENBRACKET
    	    {
    	        /* 1:270: LOGITOPENBRACKET */
    	        mLOGITOPENBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:287: LOGOPENBRACKET
    	    {
    	        /* 1:287: LOGOPENBRACKET */
    	        mLOGOPENBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:302: MINUS
    	    {
    	        /* 1:302: MINUS */
    	        mMINUS();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:308: MODEL
    	    {
    	        /* 1:308: MODEL */
    	        mMODEL();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 25:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:314: MULT
    	    {
    	        /* 1:314: MULT */
    	        mMULT();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 26:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:319: MUTLTINOMIALOPENBRACKET
    	    {
    	        /* 1:319: MUTLTINOMIALOPENBRACKET */
    	        mMUTLTINOMIALOPENBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 27:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:343: OPENBRACE
    	    {
    	        /* 1:343: OPENBRACE */
    	        mOPENBRACE();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 28:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:353: OPENBRACKET
    	    {
    	        /* 1:353: OPENBRACKET */
    	        mOPENBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 29:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:365: OPENSQUAREBRACKET
    	    {
    	        /* 1:365: OPENSQUAREBRACKET */
    	        mOPENSQUAREBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 30:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:383: PLUS
    	    {
    	        /* 1:383: PLUS */
    	        mPLUS();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 31:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:388: PROBITOPENBRACKET
    	    {
    	        /* 1:388: PROBITOPENBRACKET */
    	        mPROBITOPENBRACKET();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 32:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:406: TILDE
    	    {
    	        /* 1:406: TILDE */
    	        mTILDE();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 33:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:412: TRUNCATIONBEGIN
    	    {
    	        /* 1:412: TRUNCATIONBEGIN */
    	        mTRUNCATIONBEGIN();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 34:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:428: CONSTANTINT
    	    {
    	        /* 1:428: CONSTANTINT */
    	        mCONSTANTINT();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 35:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:440: NODENAME
    	    {
    	        /* 1:440: NODENAME */
    	        mNODENAME();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 36:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:449: CONSTANTVALUE
    	    {
    	        /* 1:449: CONSTANTVALUE */
    	        mCONSTANTVALUE();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 37:
    	    // /u/s/h/shrirams/bugsparser/Parser/BUGS.g:1:463: WHITESPACE
    	    {
    	        /* 1:463: WHITESPACE */
    	        mWHITESPACE();
    	        if  (this->hasException())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */

	}



/* End of code
 * =============================================================================
 */
