#include "BUGSParser.hpp"

using namespace BUGS;

int main(int argc, char* argv[])
    {
    BUGSLexerTraits::InputStreamType input((ANTLR_UINT8*)"Test", ANTLR_ENC_8BIT);
    BUGSLexer lxr(&input); // TLexerNew is generated by ANTLR
    BUGSParserTraits::TokenStreamType tstream(ANTLR_SIZE_HINT, lxr.get_tokSource() );
    BUGSParser psr(&tstream); // TParserNew is generated by ANTLR3

    Program program = psr.prog();
    for (std::list<Node*>::iterator it = program.nodes.begin(); it!= program.nodes.end(); ++it)
        {
        	cout << (*it)->nodename << endl;
        }
    cout << "Done Parsing";
    }
